"""Tests for issue #299: parse YAML frontmatter behind the auto-generated
leading HTML comment that ``POST /ingest`` writes for every wiki page.

Root cause covered: ``split_frontmatter`` and ``parse_markdown`` Rule 2 both
short-circuit on ``text.startswith("---\\n")``. Every wiki page produced by
``wiki_writer._render_page`` begins with a multi-line sentinel HTML comment
*before* the ``---`` fence, so the frontmatter (``type`` / ``sources`` /
``status``) was never parsed and the comment + YAML leaked into the BM25 body.

These tests assert the fix (skip a leading HTML comment before the frontmatter
detection) AND its fail-soft / regression contracts:

* parse_markdown captures ``type`` / ``sources`` / ``status`` on a
  comment-prefixed page (AC 1).
* ``retrieval._derived_from_for_section`` populates for a comment-prefixed
  concept page — closes the latent Phase-6 gap (AC 4).
* BM25 ``doc_freq`` excludes frontmatter-/comment-only tokens (AC 3).
* Regression — a page starting directly with ``---`` parses identically; a page
  with neither comment nor frontmatter keeps its body unchanged (AC 2).
* Fail-soft — unterminated comment / comment-but-no-fence degrade to
  ``({}, original_text)`` without raising (AC 6).
"""

from __future__ import annotations

from pathlib import Path

import app.indexer as indexer

# A realistic multi-line sentinel comment, mirroring
# ``wiki_writer._SENTINEL_TEMPLATE`` — the exact shape every /ingest page carries.
_SENTINEL = (
    "<!-- Auto-generated by POST /ingest on 2026-05-27T00:00:00Z.\n"
    "     Source of truth: docs/battery_care.md.\n"
    "     Manual edits will be overwritten on next ingest — edit the Source instead. -->"
)


def _page(frontmatter: str, heading: str, body: str, *, comment: bool = True) -> str:
    """Render a wiki page string in the real /ingest shape.

    ``frontmatter`` is the YAML between the ``---`` fences (no fences).
    When ``comment`` is True the page is prefixed with the multi-line sentinel
    HTML comment + a blank line, exactly as ``wiki_writer._render_page`` emits.
    """
    head = f"{_SENTINEL}\n\n" if comment else ""
    return f"{head}---\n{frontmatter}\n---\n\n# {heading}\n\n{body}\n"


# Frontmatter / comment tokens that must NEVER reach the BM25 corpus. Chosen to
# appear ONLY in the sentinel comment or the YAML frontmatter, never in the body
# (the body below is worded to avoid every one of them).
_FRONTMATTER_ONLY_TOKENS = [
    "type",
    "status",
    "concept",
    "live",
    "created",
    "updated",
    "generated",
    "ingest",
    "overwritten",
    "truth",
]

_BODY = "Charge the cell nightly and keep it away from extreme warmth to maximise lifespan."

_FRONTMATTER = (
    "id: battery-care\n"
    "type: concept\n"
    'created: "2026-05-27T00:00:00Z"\n'
    'updated: "2026-05-27T00:00:00Z"\n'
    "sources:\n"
    "  - battery_care.md#charging\n"
    "status: live\n"
    "open_questions: []"
)


# ---------------------------------------------------------------------------
# Helpers (mirror the wiki-setup pattern used across the suite)
# ---------------------------------------------------------------------------


def _setup_wiki(tmp_path: Path) -> tuple[Path, Path]:
    wiki_dir = tmp_path / "wiki"
    concepts_dir = wiki_dir / "concepts"
    concepts_dir.mkdir(parents=True)
    (wiki_dir / "entities").mkdir()
    (wiki_dir / "qa").mkdir()
    return wiki_dir, concepts_dir


def _patch_indexer(monkeypatch, tmp_path: Path, wiki_dir: Path) -> None:
    import app.logger as logger_module

    monkeypatch.setattr(indexer, "INDEX_PATH", tmp_path / ".kb" / "index.json")
    monkeypatch.setattr(indexer, "WIKI_DIR", wiki_dir)
    monkeypatch.setattr(logger_module, "LOG_PATH", wiki_dir / "log.md")
    monkeypatch.setattr(
        indexer,
        "SOURCE_DIRS",
        [wiki_dir / "entities", wiki_dir / "concepts", wiki_dir / "qa"],
    )


# ---------------------------------------------------------------------------
# AC 1 — parse_markdown captures metadata behind the comment
# ---------------------------------------------------------------------------


def test_parse_markdown_captures_metadata_behind_comment(tmp_path):
    page = tmp_path / "battery-care.md"
    page.write_text(_page(_FRONTMATTER, "Battery Care", _BODY), encoding="utf-8")

    sections = indexer.parse_markdown(page, source_id="battery-care")

    assert sections, "comment-prefixed page must still produce sections"
    md = sections[0].metadata
    assert md.get("type") == "concept", f"type not captured: {md!r}"
    assert md.get("status") == "live", f"status not captured: {md!r}"
    assert md.get("sources") == ["battery_care.md#charging"], f"sources not captured: {md!r}"


def test_parse_markdown_comment_not_in_body(tmp_path):
    """The leading sentinel comment must not survive into Section content."""
    page = tmp_path / "battery-care.md"
    page.write_text(_page(_FRONTMATTER, "Battery Care", _BODY), encoding="utf-8")

    sections = indexer.parse_markdown(page, source_id="battery-care")

    for sec in sections:
        assert "<!--" not in sec.content, f"sentinel comment leaked into body: {sec.content!r}"
        assert "Auto-generated" not in sec.content


# ---------------------------------------------------------------------------
# AC 4 — derived_from populates for a comment-prefixed concept page
# ---------------------------------------------------------------------------


def test_derived_from_populates_for_comment_prefixed_page(tmp_path, monkeypatch):
    import app.retrieval as retrieval_module

    wiki_dir, concepts_dir = _setup_wiki(tmp_path)
    (concepts_dir / "battery-care.md").write_text(
        _page(_FRONTMATTER, "Battery Care", _BODY), encoding="utf-8"
    )
    _patch_indexer(monkeypatch, tmp_path, wiki_dir)
    indexer.build_index()

    sec = next(s for s in indexer.sections if s.file == "battery-care")
    derived = retrieval_module._derived_from_for_section(sec)

    assert derived is not None, "derived_from must populate for a comment-prefixed page"
    assert any(c["source"] == "battery_care.md" for c in derived), derived


# ---------------------------------------------------------------------------
# AC 3 — frontmatter + comment tokens never reach the BM25 corpus
# ---------------------------------------------------------------------------


def test_bm25_doc_freq_excludes_frontmatter_and_comment_tokens(tmp_path, monkeypatch):
    wiki_dir, concepts_dir = _setup_wiki(tmp_path)
    (concepts_dir / "battery-care.md").write_text(
        _page(_FRONTMATTER, "Battery Care", _BODY), encoding="utf-8"
    )
    _patch_indexer(monkeypatch, tmp_path, wiki_dir)
    indexer.build_index()

    leaked = [tok for tok in _FRONTMATTER_ONLY_TOKENS if tok in indexer.doc_freq]
    assert not leaked, f"frontmatter/comment tokens leaked into BM25 doc_freq: {leaked}"
    # Sanity: a genuine body token IS indexed (proves the page was parsed at all).
    assert "lifespan" in indexer.doc_freq, "body token missing — page was not indexed"


# ---------------------------------------------------------------------------
# AC 2 — regression: no-comment pages behave byte-identically
# ---------------------------------------------------------------------------


def test_page_starting_with_dashes_parses_identically(tmp_path):
    """A page starting directly with ``---`` and the same page behind a comment
    yield the same metadata and the same body."""
    no_comment = tmp_path / "a.md"
    with_comment = tmp_path / "b.md"
    no_comment.write_text(
        _page(_FRONTMATTER, "Battery Care", _BODY, comment=False), encoding="utf-8"
    )
    with_comment.write_text(
        _page(_FRONTMATTER, "Battery Care", _BODY, comment=True), encoding="utf-8"
    )

    secs_plain = indexer.parse_markdown(no_comment, source_id="a")
    secs_comment = indexer.parse_markdown(with_comment, source_id="b")

    assert secs_plain[0].metadata.get("type") == secs_comment[0].metadata.get("type") == "concept"
    assert secs_plain[0].content == secs_comment[0].content


def test_no_frontmatter_no_comment_body_unchanged(tmp_path):
    raw = "# Plain Title\n\nJust body text with no frontmatter at all.\n"
    page = tmp_path / "plain.md"
    page.write_text(raw, encoding="utf-8")

    sections = indexer.parse_markdown(page, source_id="plain")

    assert sections[0].metadata == {"lang": "en"}, sections[0].metadata
    assert sections[0].content == "Just body text with no frontmatter at all."


# ---------------------------------------------------------------------------
# split_frontmatter — shared comment-skip convention + fail-soft
# ---------------------------------------------------------------------------


def test_split_frontmatter_skips_leading_comment():
    text = _page(_FRONTMATTER, "Battery Care", _BODY)
    metadata, body = indexer.split_frontmatter(text)

    assert metadata.get("type") == "concept"
    assert "<!--" not in body, "comment must be stripped from the returned body"
    assert body.startswith("\n# Battery Care") or body.startswith("# Battery Care"), body


def test_split_frontmatter_no_comment_byte_identical():
    text = _page(_FRONTMATTER, "Battery Care", _BODY, comment=False)
    metadata, body = indexer.split_frontmatter(text)

    assert metadata.get("status") == "live"
    assert body == text[text.index("\n---\n", 4) + 5 :]


def test_split_frontmatter_unterminated_comment_failsoft():
    text = "<!-- Auto-generated never closed\n---\ntype: concept\n---\n\nbody\n"
    metadata, body = indexer.split_frontmatter(text)

    assert metadata == {}
    assert body == text  # original text returned unchanged, never raises


def test_split_frontmatter_comment_without_frontmatter_failsoft():
    text = f"{_SENTINEL}\n\n# Heading\n\nNo frontmatter here.\n"
    metadata, body = indexer.split_frontmatter(text)

    assert metadata == {}
    assert body == text  # no frontmatter after the comment -> original text
