"""TestClient-seam tests for DELETE /pages/{slug}/aliases/{alias} (issue #491,
ADR-0030 extension).

Direct-class remove-alias: no LLM anywhere in this path — fully hermetic, no
OPENAI_API_KEY needed. Mirror-image of ``test_pages_alias_assign.py``: the
write is the same surgical frontmatter-only rewrite (``wiki_writer.
read_page_parts``) that preserves the sentinel comment, heading, body, and
citation line byte-for-byte, but this endpoint performs no collision check —
there is nothing to collide with when removing an entry.

Hermetic: ``app.indexer.WIKI_DIR`` is redirected to a tmp wiki/ pre-populated
with fixture pages, mirroring ``test_pages_alias_assign.py``'s own
conftest-free fixture style.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml
from fastapi.testclient import TestClient

import app.indexer as indexer_module

_TARGET_SLUG = "replacement-payment-methods"
_OTHER_SLUG = "shipping-policy"

_SENTINEL = (
    "<!-- Auto-generated by POST /ingest on 2026-07-03T00:00:00Z.\n"
    "     Source of truth: docs/payments.md.\n"
    "     Manual edits will be overwritten on next ingest — edit the Source instead.\n"
    "     Exception: the `aliases` field is a curator field and is preserved (ADR-0030). -->"
)


def _page_text(slug: str, *, aliases: list[str] | None = None) -> str:
    aliases_line = f"aliases: {aliases!r}\n" if aliases is not None else ""
    return (
        f"{_SENTINEL}\n\n"
        "---\n"
        f"id: {slug}\n"
        "type: concept\n"
        "created: '2026-07-03T00:00:00Z'\n"
        "updated: '2026-07-03T00:00:00Z'\n"
        "sources:\n  - payments.md#s\n"
        "status: live\n"
        "open_questions: []\n"
        "source_hashes: {}\n"
        f"{aliases_line}"
        "---\n\n"
        f"# {slug}\n\nSome content.\n\n"
        "[Source: payments.md]\n"
    )


@pytest.fixture()
def alias_wiki_dir(tmp_path: Path) -> Path:
    wiki_dir = tmp_path / "wiki"
    (wiki_dir / "concepts").mkdir(parents=True)
    (wiki_dir / "concepts" / f"{_TARGET_SLUG}.md").write_text(
        _page_text(_TARGET_SLUG, aliases=["PayPal", "venmo"]), encoding="utf-8"
    )
    (wiki_dir / "concepts" / f"{_OTHER_SLUG}.md").write_text(
        _page_text(_OTHER_SLUG, aliases=["delivery-policy"]), encoding="utf-8"
    )
    return wiki_dir


@pytest.fixture()
def alias_client(alias_wiki_dir, monkeypatch):
    monkeypatch.setattr(indexer_module, "WIKI_DIR", alias_wiki_dir)
    monkeypatch.setattr(
        indexer_module,
        "SOURCE_DIRS",
        [alias_wiki_dir / "entities", alias_wiki_dir / "concepts", alias_wiki_dir / "qa"],
    )

    from app.main import app

    return TestClient(app, raise_server_exceptions=False)


def _read_page(wiki_dir: Path, slug: str) -> str:
    return (wiki_dir / "concepts" / f"{slug}.md").read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# Success path — removal writes, everything else preserved verbatim
# ---------------------------------------------------------------------------


def test_remove_alias_succeeds_and_rewrites_frontmatter(alias_client, alias_wiki_dir):
    resp = alias_client.delete(f"/pages/{_TARGET_SLUG}/aliases/PayPal")

    assert resp.status_code == 204, resp.text
    assert resp.content == b""

    raw = _read_page(alias_wiki_dir, _TARGET_SLUG)
    fm = yaml.safe_load(raw.split("---", 2)[1])
    assert fm["aliases"] == ["venmo"], "only the named alias is removed — siblings survive"


def test_remove_alias_preserves_sentinel_heading_body_and_citation(alias_client, alias_wiki_dir):
    before = _read_page(alias_wiki_dir, _TARGET_SLUG)

    resp = alias_client.delete(f"/pages/{_TARGET_SLUG}/aliases/PayPal")
    assert resp.status_code == 204, resp.text

    after = _read_page(alias_wiki_dir, _TARGET_SLUG)
    assert after.startswith(_SENTINEL), "sentinel comment must survive byte-for-byte"
    assert after.endswith(f"# {_TARGET_SLUG}\n\nSome content.\n\n[Source: payments.md]\n")
    before_body = before.split("---", 2)[2]
    after_body = after.split("---", 2)[2]
    assert before_body == after_body


def test_remove_alias_can_clear_the_last_alias(alias_client, alias_wiki_dir):
    resp = alias_client.delete(f"/pages/{_OTHER_SLUG}/aliases/delivery-policy")
    assert resp.status_code == 204, resp.text

    raw = _read_page(alias_wiki_dir, _OTHER_SLUG)
    fm = yaml.safe_load(raw.split("---", 2)[1])
    assert fm["aliases"] == []


# ---------------------------------------------------------------------------
# Refusal paths (404 / 500) — nothing written
# ---------------------------------------------------------------------------


def test_remove_alias_404_when_slug_missing(alias_client):
    resp = alias_client.delete("/pages/no-such-page/aliases/PayPal")
    assert resp.status_code == 404


def test_remove_alias_500_on_corrupt_frontmatter(alias_client, alias_wiki_dir):
    broken = alias_wiki_dir / "concepts" / "broken-page.md"
    broken.write_text("---\nnot: [valid, yaml, :\n---\n\nBody.\n", encoding="utf-8")

    resp = alias_client.delete("/pages/broken-page/aliases/PayPal")
    assert resp.status_code == 500, resp.text


def test_remove_alias_404_when_alias_not_assigned_to_this_page(alias_client, alias_wiki_dir):
    """Removing an alias a page never declared 404s honestly rather than a
    fake-success no-op (issue #491 AC)."""
    resp = alias_client.delete(f"/pages/{_TARGET_SLUG}/aliases/never-assigned")

    assert resp.status_code == 404, resp.text
    raw = _read_page(alias_wiki_dir, _TARGET_SLUG)
    fm = yaml.safe_load(raw.split("---", 2)[1])
    assert fm["aliases"] == ["PayPal", "venmo"], "a refused removal must write nothing"


def test_remove_alias_404_when_alias_belongs_to_a_different_page(alias_client, alias_wiki_dir):
    resp = alias_client.delete(f"/pages/{_TARGET_SLUG}/aliases/delivery-policy")
    assert resp.status_code == 404, resp.text


# ---------------------------------------------------------------------------
# Path-shape guard (issue #397 precedent): a traversal-shaped slug 404s
# before any filesystem access.
# ---------------------------------------------------------------------------


def test_remove_alias_rejects_pathlike_slug_returns_404(alias_client):
    for bad in ("..\\qa\\escape-target", "D:drive-relative", ".."):
        resp = alias_client.delete(f"/pages/{bad}/aliases/PayPal")
        assert resp.status_code == 404, f"slug={bad!r} got {resp.status_code}: {resp.text}"


# ---------------------------------------------------------------------------
# No reindex — remove-alias never touches the BM25 corpus (ADR-0030 Invariant)
# ---------------------------------------------------------------------------


def test_remove_alias_triggers_no_reindex(alias_client, monkeypatch):
    import app.routes as routes_module

    calls = []
    monkeypatch.setattr(routes_module, "build_index", lambda: calls.append(1) or (0, 0))

    resp = alias_client.delete(f"/pages/{_TARGET_SLUG}/aliases/PayPal")

    assert resp.status_code == 204, resp.text
    assert calls == [], "aliases never enter BM25 — no reindex should run (ADR-0030 Invariant)"


# ---------------------------------------------------------------------------
# AC closure: removing the extra claimant's alias then re-running lint clears
# the C12 alias_vs_alias finding (over live HTTP against a real fixture, both
# endpoints through the SAME TestClient, mirroring test_pages_alias_assign.py's
# own C2-closure test one layer up).
# ---------------------------------------------------------------------------


def test_remove_alias_then_relint_clears_the_c12_alias_vs_alias_finding(
    alias_client, alias_wiki_dir, monkeypatch, tmp_path
):
    import app.lint as lint_module

    monkeypatch.setattr(lint_module, "WIKI_DIR", alias_wiki_dir)
    monkeypatch.setattr(lint_module, "DOCS_DIR", tmp_path / "docs")
    monkeypatch.setattr(lint_module, "LOG_PATH", tmp_path / "wiki" / "log.md")

    # Both fixture pages already carry an alias; make them collide on the
    # SAME alias so C12 fires an alias_vs_alias finding.
    (alias_wiki_dir / "concepts" / f"{_OTHER_SLUG}.md").write_text(
        _page_text(_OTHER_SLUG, aliases=["delivery-policy", "PayPal"]), encoding="utf-8"
    )

    before = alias_client.post("/lint", params={"include_c5": "false"})
    assert before.status_code == 200, before.text
    before_aliases = [f["alias"] for f in before.json()["findings"]["alias_collisions"]]
    assert "PayPal" in before_aliases, "the fixture must start with a colliding 'PayPal' alias"

    remove = alias_client.delete(f"/pages/{_OTHER_SLUG}/aliases/PayPal")
    assert remove.status_code == 204, remove.text

    after = alias_client.post("/lint", params={"include_c5": "false"})
    assert after.status_code == 200, after.text
    after_aliases = [f["alias"] for f in after.json()["findings"]["alias_collisions"]]
    assert "PayPal" not in after_aliases, (
        "removing the extra claimant's alias must clear the C12 finding on re-lint"
    )


def test_remove_alias_then_relint_clears_the_c12_alias_vs_slug_finding(
    alias_client, alias_wiki_dir, monkeypatch, tmp_path
):
    """Mirrors the alias_vs_alias closure test above for the OTHER C12 shape:
    a declared alias collides with an existing page's real slug (issue #491
    AC "resolves both C12 kinds")."""
    import app.lint as lint_module

    monkeypatch.setattr(lint_module, "WIKI_DIR", alias_wiki_dir)
    monkeypatch.setattr(lint_module, "DOCS_DIR", tmp_path / "docs")
    monkeypatch.setattr(lint_module, "LOG_PATH", tmp_path / "wiki" / "log.md")

    # Give the target page an alias equal to the OTHER page's real slug —
    # alias_vs_slug, not alias_vs_alias.
    (alias_wiki_dir / "concepts" / f"{_TARGET_SLUG}.md").write_text(
        _page_text(_TARGET_SLUG, aliases=["PayPal", "venmo", _OTHER_SLUG]), encoding="utf-8"
    )

    before = alias_client.post("/lint", params={"include_c5": "false"})
    assert before.status_code == 200, before.text
    before_findings = before.json()["findings"]["alias_collisions"]
    before_kind = next(f["kind"] for f in before_findings if f["alias"] == _OTHER_SLUG)
    assert before_kind == "alias_vs_slug", "the fixture must start with an alias_vs_slug collision"

    remove = alias_client.delete(f"/pages/{_TARGET_SLUG}/aliases/{_OTHER_SLUG}")
    assert remove.status_code == 204, remove.text

    after = alias_client.post("/lint", params={"include_c5": "false"})
    assert after.status_code == 200, after.text
    after_aliases = [f["alias"] for f in after.json()["findings"]["alias_collisions"]]
    assert _OTHER_SLUG not in after_aliases, (
        "removing the declaring page's alias must clear the alias_vs_slug C12 finding on re-lint"
    )
