"""TestClient-seam tests for POST /pages/{slug}/aliases (issue #409, ADR-0030
decision 3).

Direct-class assign-alias: no LLM anywhere in this path — fully hermetic, no
OPENAI_API_KEY needed. Collision detection reuses the SAME shared resolver
C2/C12 already consult (``slugs.build_alias_resolution_map``); the write is a
surgical frontmatter-only rewrite that preserves the sentinel comment,
heading, body, and citation line byte-for-byte (``wiki_writer.
read_page_parts``).

Hermetic: ``app.indexer.WIKI_DIR`` is redirected to a tmp wiki/ pre-populated
with fixture pages, mirroring ``test_pages_delete.py``'s own conftest-free
fixture style (this file is not under ``tests/lint/`` so it does not see
that subdirectory's ``tmp_wiki_dir`` conftest fixture).
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml
from fastapi.testclient import TestClient

import app.indexer as indexer_module

_TARGET_SLUG = "replacement-payment-methods"
_OTHER_SLUG = "shipping-policy"

_SENTINEL = (
    "<!-- Auto-generated by POST /ingest on 2026-07-03T00:00:00Z.\n"
    "     Source of truth: docs/payments.md.\n"
    "     Manual edits will be overwritten on next ingest — edit the Source instead.\n"
    "     Exception: the `aliases` field is a curator field and is preserved (ADR-0030). -->"
)


def _page_text(slug: str, *, aliases: list[str] | None = None) -> str:
    aliases_line = f"aliases: {aliases!r}\n" if aliases is not None else ""
    return (
        f"{_SENTINEL}\n\n"
        "---\n"
        f"id: {slug}\n"
        "type: concept\n"
        "created: '2026-07-03T00:00:00Z'\n"
        "updated: '2026-07-03T00:00:00Z'\n"
        "sources:\n  - payments.md#s\n"
        "status: live\n"
        "open_questions: []\n"
        "source_hashes: {}\n"
        f"{aliases_line}"
        "---\n\n"
        f"# {slug}\n\nSome content.\n\n"
        "[Source: payments.md]\n"
    )


@pytest.fixture()
def alias_wiki_dir(tmp_path: Path) -> Path:
    wiki_dir = tmp_path / "wiki"
    (wiki_dir / "concepts").mkdir(parents=True)
    (wiki_dir / "concepts" / f"{_TARGET_SLUG}.md").write_text(
        _page_text(_TARGET_SLUG), encoding="utf-8"
    )
    (wiki_dir / "concepts" / f"{_OTHER_SLUG}.md").write_text(
        _page_text(_OTHER_SLUG, aliases=["delivery-policy"]), encoding="utf-8"
    )
    return wiki_dir


@pytest.fixture()
def alias_client(alias_wiki_dir, monkeypatch):
    monkeypatch.setattr(indexer_module, "WIKI_DIR", alias_wiki_dir)
    monkeypatch.setattr(
        indexer_module,
        "SOURCE_DIRS",
        [alias_wiki_dir / "entities", alias_wiki_dir / "concepts", alias_wiki_dir / "qa"],
    )

    from app.main import app

    return TestClient(app, raise_server_exceptions=False)


def _read_page(wiki_dir: Path, slug: str) -> str:
    return (wiki_dir / "concepts" / f"{slug}.md").read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# Success path — assignment writes, everything else preserved verbatim
# ---------------------------------------------------------------------------


def test_assign_alias_succeeds_and_writes_frontmatter(alias_client, alias_wiki_dir):
    resp = alias_client.post(f"/pages/{_TARGET_SLUG}/aliases", json={"alias": "PayPal"})

    assert resp.status_code == 204, resp.text
    assert resp.content == b""

    raw = _read_page(alias_wiki_dir, _TARGET_SLUG)
    _, fm_text, _ = raw.split("---", 2)
    fm = yaml.safe_load(fm_text)
    assert fm["aliases"] == ["PayPal"]


def test_assign_alias_preserves_sentinel_heading_body_and_citation(alias_client, alias_wiki_dir):
    before = _read_page(alias_wiki_dir, _TARGET_SLUG)

    resp = alias_client.post(f"/pages/{_TARGET_SLUG}/aliases", json={"alias": "PayPal"})
    assert resp.status_code == 204, resp.text

    after = _read_page(alias_wiki_dir, _TARGET_SLUG)
    assert after.startswith(_SENTINEL), "sentinel comment must survive byte-for-byte"
    assert after.endswith(f"# {_TARGET_SLUG}\n\nSome content.\n\n[Source: payments.md]\n")
    # Only the frontmatter block between the fences may differ.
    before_body = before.split("---", 2)[2]
    after_body = after.split("---", 2)[2]
    assert before_body == after_body


def test_assign_alias_is_idempotent_for_the_same_page(alias_client, alias_wiki_dir):
    first = alias_client.post(f"/pages/{_TARGET_SLUG}/aliases", json={"alias": "PayPal"})
    assert first.status_code == 204, first.text

    second = alias_client.post(f"/pages/{_TARGET_SLUG}/aliases", json={"alias": "PayPal"})
    assert second.status_code == 204, second.text

    raw = _read_page(alias_wiki_dir, _TARGET_SLUG)
    fm = yaml.safe_load(raw.split("---", 2)[1])
    assert fm["aliases"] == ["PayPal"], "re-assigning the same alias must not duplicate it"


def test_assign_alias_appends_to_existing_aliases(alias_client, alias_wiki_dir):
    resp = alias_client.post(f"/pages/{_OTHER_SLUG}/aliases", json={"alias": "postage-rules"})
    assert resp.status_code == 204, resp.text

    raw = _read_page(alias_wiki_dir, _OTHER_SLUG)
    fm = yaml.safe_load(raw.split("---", 2)[1])
    assert sorted(fm["aliases"]) == ["delivery-policy", "postage-rules"]


# ---------------------------------------------------------------------------
# Refusal paths (404 / 500 / 422 / 409) — nothing written
# ---------------------------------------------------------------------------


def test_assign_alias_404_when_slug_missing(alias_client):
    resp = alias_client.post("/pages/no-such-page/aliases", json={"alias": "x"})
    assert resp.status_code == 404


def test_assign_alias_500_on_corrupt_frontmatter(alias_client, alias_wiki_dir):
    broken = alias_wiki_dir / "concepts" / "broken-page.md"
    broken.write_text("---\nnot: [valid, yaml, :\n---\n\nBody.\n", encoding="utf-8")

    resp = alias_client.post("/pages/broken-page/aliases", json={"alias": "x"})
    assert resp.status_code == 500, resp.text


def test_assign_alias_422_when_alias_is_blank(alias_client):
    resp = alias_client.post(f"/pages/{_TARGET_SLUG}/aliases", json={"alias": "   "})
    assert resp.status_code == 422, resp.text


def test_assign_alias_409_when_alias_collides_with_real_slug(alias_client, alias_wiki_dir):
    resp = alias_client.post(f"/pages/{_TARGET_SLUG}/aliases", json={"alias": _OTHER_SLUG})

    assert resp.status_code == 409, resp.text
    assert _OTHER_SLUG in resp.text
    raw = _read_page(alias_wiki_dir, _TARGET_SLUG)
    fm = yaml.safe_load(raw.split("---", 2)[1])
    assert not fm.get("aliases"), "a refused collision must write nothing"


def test_assign_alias_409_when_alias_owned_by_another_page(alias_client, alias_wiki_dir):
    resp = alias_client.post(f"/pages/{_TARGET_SLUG}/aliases", json={"alias": "delivery-policy"})

    assert resp.status_code == 409, resp.text
    assert _OTHER_SLUG in resp.text, "the 409 must name the conflicting owner"
    raw = _read_page(alias_wiki_dir, _TARGET_SLUG)
    fm = yaml.safe_load(raw.split("---", 2)[1])
    assert not fm.get("aliases")


# ---------------------------------------------------------------------------
# Path-shape guard (issue #397 precedent): a traversal-shaped slug 404s
# before any filesystem access, mirroring test_pages_delete.py's own coverage.
# ---------------------------------------------------------------------------


def test_assign_alias_rejects_pathlike_slug_returns_404(alias_client):
    # Unlike ``/pages/{slug}`` (DELETE, 2 segments), this route has a THIRD
    # segment after the slug ("/aliases"). A lone "." slug therefore does
    # NOT produce a trailing-slash artifact on normalisation — RFC 3986
    # dot-segment removal collapses "/pages/./aliases" to "/pages/aliases"
    # cleanly, which lands on the SIBLING DELETE /pages/{slug} route
    # (slug="aliases") and 405s there instead of ever reaching this handler.
    # That is a pre-existing routing/normalisation quirk exercised directly
    # against ``is_bare_slug`` (test_paths_is_bare_slug.py), not a gap in
    # this guard — "." is intentionally omitted here, mirroring how
    # test_pages_delete.py omits "/" from its own route-level list for the
    # analogous reason.
    for bad in ("..\\qa\\escape-target", "D:drive-relative", ".."):
        resp = alias_client.post(f"/pages/{bad}/aliases", json={"alias": "x"})
        assert resp.status_code == 404, f"slug={bad!r} got {resp.status_code}: {resp.text}"


# ---------------------------------------------------------------------------
# No reindex — assign-alias never touches the BM25 corpus (ADR-0030 Invariant)
# ---------------------------------------------------------------------------


def test_assign_alias_triggers_no_reindex(alias_client, monkeypatch):
    import app.routes as routes_module

    calls = []
    monkeypatch.setattr(routes_module, "build_index", lambda: calls.append(1) or (0, 0))

    resp = alias_client.post(f"/pages/{_TARGET_SLUG}/aliases", json={"alias": "PayPal"})

    assert resp.status_code == 204, resp.text
    assert calls == [], "aliases never enter BM25 — no reindex should run (ADR-0030 Invariant)"
