"""TestClient-seam tests for GET /pages/resolution-map (issue #410, ADR-0030
decision 5).

Read-only linkify resolution map: no LLM, no write, no lock — fully hermetic,
no OPENAI_API_KEY needed. Both response fields derive from the SAME shared
resolver ``slugs.build_alias_resolution_map`` already exercised by
``test_pages_alias_assign.py`` / ``test_slugs_alias_resolution.py``, so a
wikilink resolves here iff C2 would not flag it as red for the same corpus.

Hermetic: ``app.indexer.WIKI_DIR`` is redirected to a tmp wiki/ pre-populated
with fixture pages, mirroring ``test_pages_alias_assign.py``'s own
conftest-free fixture style.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from fastapi.testclient import TestClient

import app.indexer as indexer_module

_SENTINEL = (
    "<!-- Auto-generated by POST /ingest on 2026-07-03T00:00:00Z.\n"
    "     Source of truth: docs/payments.md.\n"
    "     Manual edits will be overwritten on next ingest — edit the Source instead.\n"
    "     Exception: the `aliases` field is a curator field and is preserved (ADR-0030). -->"
)


def _page_text(slug: str, *, aliases: list[str] | None = None) -> str:
    aliases_line = f"aliases: {aliases!r}\n" if aliases is not None else ""
    return (
        f"{_SENTINEL}\n\n"
        "---\n"
        f"id: {slug}\n"
        "type: concept\n"
        "created: '2026-07-03T00:00:00Z'\n"
        "updated: '2026-07-03T00:00:00Z'\n"
        "sources:\n  - payments.md#s\n"
        "status: live\n"
        "open_questions: []\n"
        "source_hashes: {}\n"
        f"{aliases_line}"
        "---\n\n"
        f"# {slug}\n\nSome content mentioning [[{slug}]].\n\n"
        "[Source: payments.md]\n"
    )


@pytest.fixture()
def resolution_wiki_dir(tmp_path: Path) -> Path:
    wiki_dir = tmp_path / "wiki"
    (wiki_dir / "concepts").mkdir(parents=True)
    (wiki_dir / "entities").mkdir(parents=True)
    (wiki_dir / "concepts" / "replacement-payment-methods.md").write_text(
        _page_text("replacement-payment-methods", aliases=["paypal", "venmo"]),
        encoding="utf-8",
    )
    (wiki_dir / "concepts" / "shipping-policy.md").write_text(
        _page_text("shipping-policy"), encoding="utf-8"
    )
    (wiki_dir / "entities" / "acme-shop.md").write_text(_page_text("acme-shop"), encoding="utf-8")
    return wiki_dir


@pytest.fixture()
def resolution_client(resolution_wiki_dir, monkeypatch):
    monkeypatch.setattr(indexer_module, "WIKI_DIR", resolution_wiki_dir)
    monkeypatch.setattr(
        indexer_module,
        "SOURCE_DIRS",
        [
            resolution_wiki_dir / "entities",
            resolution_wiki_dir / "concepts",
            resolution_wiki_dir / "qa",
        ],
    )

    from app.main import app

    return TestClient(app, raise_server_exceptions=False)


# ---------------------------------------------------------------------------
# Happy path: real slugs get their relpath, aliases get their canonical slug
# ---------------------------------------------------------------------------


def test_resolution_map_returns_200(resolution_client):
    resp = resolution_client.get("/pages/resolution-map")
    assert resp.status_code == 200, resp.text


def test_real_slugs_map_to_their_relpath(resolution_client):
    data = resolution_client.get("/pages/resolution-map").json()

    assert data["slugs"]["shipping-policy"] == "wiki/concepts/shipping-policy.md"
    assert data["slugs"]["acme-shop"] == "wiki/entities/acme-shop.md"
    assert data["slugs"]["replacement-payment-methods"] == (
        "wiki/concepts/replacement-payment-methods.md"
    )


def test_aliases_map_to_canonical_slug_not_relpath(resolution_client):
    data = resolution_client.get("/pages/resolution-map").json()

    assert data["aliases"]["paypal"] == "replacement-payment-methods"
    assert data["aliases"]["venmo"] == "replacement-payment-methods"
    # A client resolves an alias's relpath through `slugs`, not a duplicate here.
    assert "paypal" not in data["slugs"]


def test_unresolvable_string_appears_in_neither_field(resolution_client):
    data = resolution_client.get("/pages/resolution-map").json()

    assert "not-a-real-slug-or-alias" not in data["slugs"]
    assert "not-a-real-slug-or-alias" not in data["aliases"]


def test_empty_corpus_returns_empty_maps(tmp_path, monkeypatch):
    wiki_dir = tmp_path / "wiki"
    wiki_dir.mkdir()
    monkeypatch.setattr(indexer_module, "WIKI_DIR", wiki_dir)

    from app.main import app

    client = TestClient(app, raise_server_exceptions=False)
    resp = client.get("/pages/resolution-map")

    assert resp.status_code == 200, resp.text
    assert resp.json() == {"slugs": {}, "aliases": {}}


# ---------------------------------------------------------------------------
# Agreement with C2: this endpoint and the lint report must never disagree
# (ADR-0030 Invariant — one shared resolver for every consumer)
# ---------------------------------------------------------------------------


def test_resolution_map_agrees_with_c2_red_link_report(
    resolution_client, resolution_wiki_dir, monkeypatch, tmp_path
):
    import app.lint as lint_module

    monkeypatch.setattr(lint_module, "WIKI_DIR", resolution_wiki_dir)
    monkeypatch.setattr(lint_module, "DOCS_DIR", tmp_path / "docs")
    monkeypatch.setattr(lint_module, "LOG_PATH", tmp_path / "wiki" / "log.md")

    (resolution_wiki_dir / "concepts" / "referrer-page.md").write_text(
        "---\n"
        "id: referrer-page\n"
        "type: concept\n"
        "created: '2026-07-03T00:00:00Z'\n"
        "updated: '2026-07-03T00:00:00Z'\n"
        "sources:\n  - payments.md#s\n"
        "status: live\n"
        "open_questions: []\n"
        "source_hashes: {}\n"
        "---\n\n"
        "# referrer-page\n\nSee [[totally-unresolvable]] for details.\n"
        "\n[Source: payments.md]\n",
        encoding="utf-8",
    )

    lint_resp = resolution_client.post("/lint", params={"include_c5": "false"})
    assert lint_resp.status_code == 200, lint_resp.text
    red_slugs = {f["slug"] for f in lint_resp.json()["findings"]["red_links"]}
    assert "totally-unresolvable" in red_slugs

    map_resp = resolution_client.get("/pages/resolution-map")
    data = map_resp.json()
    assert "totally-unresolvable" not in data["slugs"]
    assert "totally-unresolvable" not in data["aliases"]

    # And a resolvable link (the self-mention every fixture page carries)
    # must NOT be red, agreeing with the map's resolvability.
    assert "shipping-policy" not in red_slugs
    assert "shipping-policy" in data["slugs"]


# ---------------------------------------------------------------------------
# Path-shape / contract isolation
# ---------------------------------------------------------------------------


def test_resolution_map_does_not_disturb_read_file_contract(resolution_client):
    """AC: /read/file's response body stays byte-identical (contract untouched)."""
    resp = resolution_client.get(
        "/pages/resolution-map"
    )  # exercised first to rule out shared-state leakage
    assert resp.status_code == 200

    # /read/file lives on the Gateway, not this sub-app — this test only
    # asserts the resolution-map route doesn't shadow or interfere with any
    # existing /pages/* route on THIS router.
    delete_resp = resolution_client.delete("/pages/no-such-slug")
    assert delete_resp.status_code == 404, "sibling /pages/{slug} route must still work"
