"""Integration tests for wiki_index wiring into /index — Slice #2 (issue #20).

Covers all Acceptance Criteria from issue #20:
- AC 4/5: Happy-path /index returns all five IndexResponse fields; wiki/index.md written.
- AC 6: Wiki-failure path /index still returns 200 with correct failure fields.
- AC 7: /chat works after a /index call that experienced a wiki write failure.

All tests use the real Section Index (REAL_DOCS) and a fake LLM for /chat assertions.
No live OpenAI calls.

Imports of app.* modules are deferred to inside each test function so that the
module-reload done by test_persistence.py (sys.modules cleanup) does not leave
stale references here.
"""

from __future__ import annotations

import pytest
from fastapi.testclient import TestClient

from .conftest import REAL_DOCS, FakeLLMResponse

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

REFUND_SECTION_ID = "refund_policy.md#refund-timeline"
WIKI_INDEX_HEADER_FRAGMENT = "<!-- Auto-generated by POST /index"


# ---------------------------------------------------------------------------
# Helpers (no app.* at module level)
# ---------------------------------------------------------------------------


class FakeLLM:
    """Minimal LLM stub returning a canned grounded answer."""

    def __init__(self, source_id: str = REFUND_SECTION_ID):
        self.source_id = source_id

    def invoke(self, messages: list):
        return FakeLLMResponse(
            content=(
                f"Approved refunds are processed within 5-7 business days. "
                f"[Source: {self.source_id}]"
            )
        )


def _make_approved_outcome(source_id: str):
    from app.grounding import GroundingClaim, GroundingOutcome, GroundingResult

    return GroundingOutcome(
        passed=True,
        reason="claim_supported",
        result=GroundingResult(
            reasoning="All claims trace to the cited section.",
            claims=[
                GroundingClaim(
                    text="Approved refunds are processed within 5-7 business days.",
                    supported=True,
                    citing_section_ids=[source_id],
                )
            ],
            unsupported_claims=[],
            passed=True,
        ),
        retries_attempted=0,
    )


# ---------------------------------------------------------------------------
# AC 4+5: Happy-path test
# POST /index returns 200; all five IndexResponse fields correct;
# wiki/index.md created with correct header.
# ---------------------------------------------------------------------------


def test_index_happy_path_all_five_fields(tmp_path, monkeypatch):
    """POST /index returns all five IndexResponse fields; wiki/index.md written."""
    import app.indexer as _indexer
    import app.logger as _logger

    # Redirect log path and index path to tmp
    monkeypatch.setattr(_logger, "LOG_PATH", tmp_path / "wiki" / "log.md")
    monkeypatch.setattr(_indexer, "INDEX_PATH", tmp_path / ".kb" / "index.json")

    # Redirect WIKI_DIR on the indexer module — write_wiki_index reads it from
    # ``indexer`` at call time so this propagates correctly without the
    # import-time-binding pitfall.
    wiki_dir = tmp_path / "wiki"
    monkeypatch.setattr(_indexer, "WIKI_DIR", wiki_dir)

    from app.main import app

    client = TestClient(app)
    resp = client.post("/index")

    assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"
    body = resp.json()

    # All five fields present
    assert body["files_indexed"] == 3, f"Expected 3, got {body['files_indexed']}"
    assert body["sections_indexed"] == 9, f"Expected 9, got {body['sections_indexed']}"
    assert body["wiki_index_written"] is True, (
        f"Expected wiki_index_written=True, got {body['wiki_index_written']}"
    )
    assert body["wiki_index_path"] is not None, "Expected wiki_index_path to be a string"
    assert body["wiki_index_path"].endswith("wiki/index.md") or body["wiki_index_path"].endswith(
        "wiki\\index.md"
    ), f"Expected path ending with wiki/index.md, got {body['wiki_index_path']!r}"
    assert body["wiki_index_error"] is None, (
        f"Expected wiki_index_error=None, got {body['wiki_index_error']!r}"
    )

    # Filesystem assertion: wiki/index.md exists with correct header
    wiki_index_path = wiki_dir / "index.md"
    assert wiki_index_path.exists(), "wiki/index.md must exist after happy-path /index"
    content = wiki_index_path.read_text(encoding="utf-8")
    assert content.startswith(WIKI_INDEX_HEADER_FRAGMENT), (
        f"wiki/index.md must start with HTML comment header, got:\n{content[:200]}"
    )


# ---------------------------------------------------------------------------
# AC 6: Wiki write failure test
# POST /index still returns 200; section index unaffected; wiki fields carry failure.
# Log entry written for wiki_index_error.
# ---------------------------------------------------------------------------


def test_index_wiki_failure_returns_200_with_failure_fields(tmp_path, monkeypatch):
    """POST /index returns 200 even when write_wiki_index fails; response carries failure info."""
    import app.indexer as _indexer
    import app.logger as _logger
    import app.wiki_index as _wiki_index_module

    monkeypatch.setattr(_logger, "LOG_PATH", tmp_path / "wiki" / "log.md")
    monkeypatch.setattr(_indexer, "INDEX_PATH", tmp_path / ".kb" / "index.json")

    # Redirect WIKI_DIR on the indexer module (read at call time inside
    # write_wiki_index — see test_index_happy_path_all_five_fields).
    wiki_dir = tmp_path / "wiki"
    monkeypatch.setattr(_indexer, "WIKI_DIR", wiki_dir)

    # Monkey-patch write_wiki_index to simulate failure
    monkeypatch.setattr(
        _wiki_index_module,
        "write_wiki_index",
        lambda sections, wiki_dir=None: (False, None, "PermissionError: simulated"),
    )

    from app.main import app

    client = TestClient(app)
    resp = client.post("/index")

    assert resp.status_code == 200, f"Expected 200 even on wiki failure, got {resp.status_code}"
    body = resp.json()

    # Section Index fields unaffected
    assert body["files_indexed"] == 3, f"Expected 3, got {body['files_indexed']}"
    assert body["sections_indexed"] == 9, f"Expected 9, got {body['sections_indexed']}"

    # Wiki failure fields
    assert body["wiki_index_written"] is False, (
        f"Expected wiki_index_written=False, got {body['wiki_index_written']}"
    )
    assert body["wiki_index_path"] is None, (
        f"Expected wiki_index_path=None, got {body['wiki_index_path']!r}"
    )
    assert body["wiki_index_error"] == "PermissionError: simulated", (
        f"Expected error='PermissionError: simulated', got {body['wiki_index_error']!r}"
    )

    # wiki/index.md was NOT created (write_wiki_index was mocked to fail)
    assert not (wiki_dir / "index.md").exists(), (
        "wiki/index.md must NOT exist when write_wiki_index returns failure"
    )

    # Log entry for wiki_index_error was written
    log_path = tmp_path / "wiki" / "log.md"
    assert log_path.exists(), "wiki/log.md must exist after /index (for the index_built log entry)"
    log_content = log_path.read_text(encoding="utf-8")
    assert "wiki_index_error" in log_content, (
        f"Expected 'wiki_index_error' in log, got:\n{log_content}"
    )
    assert "PermissionError: simulated" in log_content, (
        f"Expected failure reason in log, got:\n{log_content}"
    )


# ---------------------------------------------------------------------------
# AC 7: /chat works after wiki-failure /index
# Section Index is still searchable; grounded answer returns correctly.
# ---------------------------------------------------------------------------


def test_chat_works_after_wiki_failure_index(tmp_path, monkeypatch):
    """/chat returns a grounded answer after an /index call with wiki write failure."""
    import app.indexer as _indexer
    import app.logger as _logger
    import app.retrieval as _retrieval_module
    import app.wiki_index as _wiki_index_module

    monkeypatch.setattr(_logger, "LOG_PATH", tmp_path / "wiki" / "log.md")
    monkeypatch.setattr(_indexer, "INDEX_PATH", tmp_path / ".kb" / "index.json")

    wiki_dir = tmp_path / "wiki"
    monkeypatch.setattr(_indexer, "WIKI_DIR", wiki_dir)

    # Simulate wiki write failure
    monkeypatch.setattr(
        _wiki_index_module,
        "write_wiki_index",
        lambda sections, wiki_dir=None: (False, None, "PermissionError: simulated"),
    )

    # Inject fake LLM and verifier for /chat
    fake_llm = FakeLLM(source_id=REFUND_SECTION_ID)
    monkeypatch.setattr(_retrieval_module, "_llm", fake_llm)
    monkeypatch.setattr(_retrieval_module, "get_llm", lambda: fake_llm)
    monkeypatch.setattr(
        _retrieval_module.grounding_module,
        "verify",
        lambda draft, sections: _make_approved_outcome(REFUND_SECTION_ID),
    )

    from app.main import app

    client = TestClient(app)

    # Step 1: /index with wiki failure
    index_resp = client.post("/index")
    assert index_resp.status_code == 200
    assert index_resp.json()["wiki_index_written"] is False  # wiki failed

    # Step 2: /chat still works (Section Index was built despite wiki failure)
    chat_resp = client.post("/chat", json={"query": "How long do refunds take?"})
    assert chat_resp.status_code == 200, (
        f"Expected 200 from /chat after wiki failure, got {chat_resp.status_code}: {chat_resp.text}"
    )
    body = chat_resp.json()
    assert "answer" in body
    assert REFUND_SECTION_ID in body["answer"], (
        f"Expected refund citation in answer, got: {body['answer']}"
    )
    assert body["grounding"]["passed"] is True, (
        f"Expected grounding.passed=True, got {body['grounding']}"
    )
