"""Unit tests for wiki_writer.py — frontmatter YAML round-trip, sentinel comment,
atomic write (no .tmp lingers).

All tests are hermetic (no OPENAI_API_KEY required, no LLM calls).

AC coverage:
  - Atomic write: no .tmp file lingers in wiki/concepts/ after success
  - wiki/concepts/<slug>.md has all 7 frontmatter fields
  - Sentinel comment present and correct
  - [Source: ...] citation line present
  - YAML frontmatter round-trips through yaml.safe_load correctly
"""

from __future__ import annotations

import datetime

import yaml

from app.schemas import WikiPageDraft, WikiPageFrontmatter
from app.wiki_writer import write_pages_for_source

# ---------------------------------------------------------------------------
# Helpers / fixtures
# ---------------------------------------------------------------------------

FIXED_TS = "2026-05-26T14:30:00Z"


def _make_draft(
    slug: str = "cancellation-window",
    source: str = "refund_policy.md",
    body: str = "Customers can cancel within 24 hours.",
    open_questions: list | None = None,
) -> WikiPageDraft:
    """Return a fully-populated WikiPageDraft for testing."""
    if open_questions is None:
        open_questions = []
    citation_id = f"{source}#{slug}"
    frontmatter = WikiPageFrontmatter(
        id=slug,
        type="concept",
        created=FIXED_TS,
        updated=FIXED_TS,
        sources=[citation_id],
        status="live",
        open_questions=open_questions,
    )
    return WikiPageDraft(
        frontmatter=frontmatter,
        body=body,
        citation_line=f"[Source: {citation_id}]",
        slug=slug,
    )


# ---------------------------------------------------------------------------
# AC: page file exists with correct slug-based filename
# ---------------------------------------------------------------------------


def test_write_creates_file_at_correct_path(tmp_path):
    draft = _make_draft()
    result = write_pages_for_source("refund_policy.md", [draft], wiki_dir=tmp_path)

    assert result.errors == [], f"Expected no errors, got: {result.errors}"
    page_path = tmp_path / "concepts" / "cancellation-window.md"
    assert page_path.exists(), f"Expected {page_path} to exist"
    assert result.pages_written == ["concepts/cancellation-window.md"]


# ---------------------------------------------------------------------------
# AC: sentinel HTML comment present with correct fields
# ---------------------------------------------------------------------------


def test_sentinel_comment_present(tmp_path):
    draft = _make_draft()
    write_pages_for_source("refund_policy.md", [draft], wiki_dir=tmp_path)

    content = (tmp_path / "concepts" / "cancellation-window.md").read_text(encoding="utf-8")

    assert "<!-- Auto-generated by POST /ingest on" in content, (
        f"Sentinel comment header missing.\nContent:\n{content}"
    )
    assert "Source of truth: docs/refund_policy.md." in content, (
        f"Sentinel source-of-truth line missing.\nContent:\n{content}"
    )
    assert "Manual edits will be overwritten on next ingest" in content, (
        f"Sentinel warning line missing.\nContent:\n{content}"
    )


# ---------------------------------------------------------------------------
# AC: all 7 frontmatter fields present and YAML-parseable
# ---------------------------------------------------------------------------


def test_frontmatter_yaml_round_trip(tmp_path):
    """YAML frontmatter round-trips through yaml.safe_load with all 7 fields."""
    draft = _make_draft(open_questions=["What about partial cancellations?"])
    write_pages_for_source("refund_policy.md", [draft], wiki_dir=tmp_path)

    content = (tmp_path / "concepts" / "cancellation-window.md").read_text(encoding="utf-8")

    # Extract YAML between the --- delimiters (skip sentinel, find first --- block)
    lines = content.splitlines()
    # Find first "---" after the sentinel comment
    dash_indices = [i for i, line in enumerate(lines) if line.strip() == "---"]
    assert len(dash_indices) >= 2, f"Expected at least 2 '---' delimiters, got: {dash_indices}"

    fm_start = dash_indices[0] + 1
    fm_end = dash_indices[1]
    fm_text = "\n".join(lines[fm_start:fm_end])
    parsed = yaml.safe_load(fm_text)

    # All 7 fields must be present
    required_fields = {"id", "type", "created", "updated", "sources", "status", "open_questions"}
    assert required_fields.issubset(parsed.keys()), (
        f"Missing frontmatter fields: {required_fields - parsed.keys()}\nParsed: {parsed}"
    )

    assert parsed["id"] == "cancellation-window"
    assert parsed["type"] == "concept"
    assert parsed["created"] == FIXED_TS
    assert parsed["updated"] == FIXED_TS
    assert parsed["sources"] == ["refund_policy.md#cancellation-window"]
    assert parsed["status"] == "live"
    assert parsed["open_questions"] == ["What about partial cancellations?"]


# ---------------------------------------------------------------------------
# AC: citation line present
# ---------------------------------------------------------------------------


def test_citation_line_present(tmp_path):
    """[Source: ...] citation line appears at the bottom of the page."""
    draft = _make_draft()
    write_pages_for_source("refund_policy.md", [draft], wiki_dir=tmp_path)

    content = (tmp_path / "concepts" / "cancellation-window.md").read_text(encoding="utf-8")

    assert "[Source: refund_policy.md#cancellation-window]" in content, (
        f"Citation line missing.\nContent:\n{content}"
    )


# ---------------------------------------------------------------------------
# AC: atomic write — no .tmp file lingers after success
# ---------------------------------------------------------------------------


def test_no_tmp_file_lingers_after_success(tmp_path):
    """After a successful write, no .tmp files should remain in wiki/concepts/."""
    draft = _make_draft()
    write_pages_for_source("refund_policy.md", [draft], wiki_dir=tmp_path)

    concepts_dir = tmp_path / "concepts"
    tmp_files = list(concepts_dir.glob("*.tmp"))
    assert tmp_files == [], f"Stale .tmp files found after successful write: {tmp_files}"


# ---------------------------------------------------------------------------
# AC: LLM body content appears in the file
# ---------------------------------------------------------------------------


def test_body_content_written(tmp_path):
    """The LLM-generated body text appears in the page file."""
    body = "Customers can cancel their order within 24 hours of purchase."
    draft = _make_draft(body=body)
    write_pages_for_source("refund_policy.md", [draft], wiki_dir=tmp_path)

    content = (tmp_path / "concepts" / "cancellation-window.md").read_text(encoding="utf-8")

    assert body in content, f"LLM body missing from page.\nContent:\n{content}"


# ---------------------------------------------------------------------------
# AC: empty open_questions serialises as empty YAML list
# ---------------------------------------------------------------------------


def test_empty_open_questions_serialises_correctly(tmp_path):
    """open_questions=[] must serialise as an empty YAML list, not null."""
    draft = _make_draft(open_questions=[])
    write_pages_for_source("refund_policy.md", [draft], wiki_dir=tmp_path)

    content = (tmp_path / "concepts" / "cancellation-window.md").read_text(encoding="utf-8")

    # YAML: "open_questions: []\n" or "open_questions:\n" (both are valid empty lists)
    # Parse to verify
    lines = content.splitlines()
    dash_indices = [i for i, line in enumerate(lines) if line.strip() == "---"]
    fm_text = "\n".join(lines[dash_indices[0] + 1 : dash_indices[1]])
    parsed = yaml.safe_load(fm_text)

    assert parsed["open_questions"] == [], (
        f"Expected open_questions=[], got: {parsed['open_questions']!r}"
    )
