"""Golden test: entity template output matches EXPECTED literal byte-exactly.

Covers AC: `markdown_kb/tests/ingest/test_entity_template.py` — golden test:
mock-LLM-driven entity output matches `EXPECTED` literal byte-exactly.

The mock LLM returns a fixed body and empty open_questions so the output is
100% deterministic.  LangChain types are confined to templates.py per
CODING_STANDARD §2.4 — this test only imports from app.schemas and
app.templates.

Hermetic: no OPENAI_API_KEY required.
"""

from __future__ import annotations

import datetime
from unittest.mock import MagicMock

import app.templates as templates_module
from app.indexer import Section, slugify
from app.templates import generate_entity_page

# ---------------------------------------------------------------------------
# Fixed test data
# ---------------------------------------------------------------------------

FIXED_TS = "2026-05-26T14:30:00Z"
FIXED_NOW = datetime.datetime(2026, 5, 26, 14, 30, 0, tzinfo=datetime.UTC)

SOURCE_FILENAME = "my_product.md"
SOURCE_STEM = "my_product"

SECTIONS = [
    Section(
        id="my_product.md#overview",
        file="my_product.md",
        heading="Overview",
        heading_path=["Overview"],
        content="A great product that solves customer problems reliably.",
        tokens=["great", "product", "solves", "customer", "problems", "reliably"],
    ),
    Section(
        id="my_product.md#features",
        file="my_product.md",
        heading="Features",
        heading_path=["Features"],
        content="Fast, reliable, and easy to use.",
        tokens=["fast", "reliable", "easy", "use"],
    ),
]

FIXED_BODY = (
    "My Product is a reliable solution that helps customers solve their problems. "
    "It features fast performance and is easy to use."
)

# ---------------------------------------------------------------------------
# Expected output — golden literal
# ---------------------------------------------------------------------------

# This string is the EXACT expected output of generate_entity_page() when
# the LLM returns FIXED_BODY with empty open_questions.
# The frontmatter YAML order matches PyYAML's default_flow_style=False output.
EXPECTED = """\
<!-- Auto-generated by POST /ingest on 2026-05-26T14:30:00Z.
     Source of truth: docs/my_product.md.
     Manual edits will be overwritten on next ingest — edit the Source instead. -->

---
created: '2026-05-26T14:30:00Z'
id: my-product
open_questions: []
sources:
- my_product.md#overview
- my_product.md#features
status: live
type: entity
updated: '2026-05-26T14:30:00Z'
---

# My Product

My Product is a reliable solution that helps customers solve their problems. It features fast performance and is easy to use.

[Source: my_product.md]
"""


# ---------------------------------------------------------------------------
# Fake LLM
# ---------------------------------------------------------------------------


class _FakeSynthesisOutput:
    def __init__(self):
        self.body = FIXED_BODY
        self.open_questions = []


def _make_fake_llm() -> MagicMock:
    fake_llm = MagicMock()
    fake_chain = MagicMock()
    fake_chain.invoke.return_value = _FakeSynthesisOutput()
    fake_llm.with_structured_output.return_value = fake_chain
    return fake_llm


# ---------------------------------------------------------------------------
# Golden test
# ---------------------------------------------------------------------------


def test_entity_template_golden_output(monkeypatch):
    """generate_entity_page() output matches EXPECTED byte-exactly."""
    fake_llm = _make_fake_llm()
    monkeypatch.setattr(templates_module, "_ingest_llm", fake_llm)
    monkeypatch.setattr(templates_module, "get_ingest_llm", lambda: fake_llm)

    draft = generate_entity_page(
        SECTIONS,
        source_stem=SOURCE_STEM,
        source_filename=SOURCE_FILENAME,
        now=FIXED_NOW,
    )

    # Verify slug
    assert draft.slug == slugify(SOURCE_STEM), (
        f"Expected slug='{slugify(SOURCE_STEM)}', got: {draft.slug!r}"
    )

    # Render the page using wiki_writer to get the full text
    from app.wiki_writer import _render_page

    rendered = _render_page(SOURCE_FILENAME, draft)

    assert rendered == EXPECTED, (
        f"Entity template output does not match EXPECTED.\n"
        f"--- EXPECTED ---\n{EXPECTED!r}\n"
        f"--- GOT ---\n{rendered!r}"
    )
