"""Golden test: concept template output matches EXPECTED literal byte-exactly.

Covers AC: `markdown_kb/tests/ingest/test_concept_template.py` — golden test:
mock-LLM-driven concept output matches `EXPECTED` literal byte-exactly.

The mock LLM returns a fixed body and empty open_questions so the output is
100% deterministic.  LangChain types are confined to templates.py per
CODING_STANDARD §2.4 — this test only imports from app.schemas and
app.templates.

Hermetic: no OPENAI_API_KEY required.
"""

from __future__ import annotations

import datetime
from unittest.mock import MagicMock

import app.templates as templates_module
from app.indexer import Section
from app.templates import generate_page

# ---------------------------------------------------------------------------
# Fixed test data
# ---------------------------------------------------------------------------

FIXED_TS = "2026-05-26T14:30:00Z"
FIXED_NOW = datetime.datetime(2026, 5, 26, 14, 30, 0, tzinfo=datetime.UTC)

SOURCE_FILENAME = "refund_policy.md"

SECTION = Section(
    id="refund_policy.md#cancellation-window",
    file="refund_policy.md",
    heading="Cancellation Window",
    heading_path=["Cancellation Window"],
    content=(
        "Customers can cancel an order within 24 hours after purchase "
        "if the order has not shipped yet."
    ),
    tokens=["customers", "cancel", "order", "24", "hours", "purchase", "shipped"],
)

FIXED_BODY = (
    "Customers can cancel an order within 24 hours of purchase if it has not shipped. "
    "After shipping, they must request a return instead."
)

# ---------------------------------------------------------------------------
# Expected output — golden literal
# ---------------------------------------------------------------------------

# This string is the EXACT expected output of generate_page() for the
# "concept" path when the LLM returns FIXED_BODY with empty open_questions.
# The frontmatter YAML order matches PyYAML's default_flow_style=False output.
EXPECTED = """\
<!-- Auto-generated by POST /ingest on 2026-05-26T14:30:00Z.
     Source of truth: docs/refund_policy.md.
     Manual edits will be overwritten on next ingest — edit the Source instead.
     Exception: the `aliases` field is a curator field and is preserved (ADR-0030). -->

---
aliases: []
created: '2026-05-26T14:30:00Z'
id: cancellation-window
open_questions: []
source_hashes: {}
sources:
- refund_policy.md#cancellation-window
status: live
type: concept
updated: '2026-05-26T14:30:00Z'
---

# Cancellation Window

Customers can cancel an order within 24 hours of purchase if it has not shipped. After shipping, they must request a return instead.

[Source: refund_policy.md#cancellation-window]
"""


# ---------------------------------------------------------------------------
# Fake LLM
# ---------------------------------------------------------------------------


class _FakeSynthesisOutput:
    def __init__(self):
        self.body = FIXED_BODY
        self.open_questions = []


def _make_fake_llm() -> MagicMock:
    fake_llm = MagicMock()
    fake_chain = MagicMock()
    fake_chain.invoke.return_value = _FakeSynthesisOutput()
    fake_llm.with_structured_output.return_value = fake_chain
    return fake_llm


# ---------------------------------------------------------------------------
# Golden test
# ---------------------------------------------------------------------------


def test_concept_template_golden_output(monkeypatch):
    """generate_page() for concept output matches EXPECTED byte-exactly."""
    fake_llm = _make_fake_llm()
    monkeypatch.setattr(templates_module, "_ingest_llm", fake_llm)
    monkeypatch.setattr(templates_module, "get_ingest_llm", lambda: fake_llm)

    draft = generate_page(SECTION, "concept", now=FIXED_NOW)

    # Verify slug and frontmatter fields
    assert draft.slug == "cancellation-window", (
        f"Expected slug='cancellation-window', got: {draft.slug!r}"
    )
    assert draft.frontmatter.type == "concept"
    assert draft.frontmatter.id == "cancellation-window"
    assert draft.frontmatter.sources == ["refund_policy.md#cancellation-window"]
    assert draft.frontmatter.status == "live"
    assert draft.frontmatter.open_questions == []

    # Render the page using wiki_writer to get the full text
    from app.wiki_writer import _render_page

    rendered = _render_page(SOURCE_FILENAME, draft)

    assert rendered == EXPECTED, (
        f"Concept template output does not match EXPECTED.\n"
        f"--- EXPECTED ---\n{EXPECTED!r}\n"
        f"--- GOT ---\n{rendered!r}"
    )
