"""Unit tests for ``wiki_writer.read_page_parts`` (issue #409, ADR-0030).

Split-only helper feeding ``pages.add_alias``'s surgical frontmatter rewrite:
returns ``(prefix, frontmatter_dict, suffix)`` so a caller can rewrite ONLY
the frontmatter block and reassemble byte-identical output for everything
else. Hermetic — no filesystem dependency beyond ``tmp_path``, no
OPENAI_API_KEY.
"""

from __future__ import annotations

from pathlib import Path

from app.wiki_writer import read_page_parts

_PAGE_TEXT = (
    "<!-- Auto-generated by POST /ingest on 2026-07-03T00:00:00Z. -->\n"
    "\n"
    "---\n"
    "id: some-page\n"
    "type: concept\n"
    "aliases: []\n"
    "---\n"
    "\n"
    "# Some Page\n"
    "\n"
    "Body text.\n"
    "\n"
    "[Source: policy.md]\n"
)


def test_read_page_parts_splits_prefix_frontmatter_suffix(tmp_path: Path):
    path = tmp_path / "page.md"
    path.write_text(_PAGE_TEXT, encoding="utf-8")

    result = read_page_parts(path)

    assert result is not None
    prefix, fm, suffix = result
    assert prefix == "<!-- Auto-generated by POST /ingest on 2026-07-03T00:00:00Z. -->\n\n---\n"
    assert fm == {"id": "some-page", "type": "concept", "aliases": []}
    assert suffix == "---\n\n# Some Page\n\nBody text.\n\n[Source: policy.md]\n"


def test_read_page_parts_reassembly_round_trips_unchanged(tmp_path: Path):
    path = tmp_path / "page.md"
    path.write_text(_PAGE_TEXT, encoding="utf-8")

    prefix, fm, suffix = read_page_parts(path)
    import yaml

    fm_text = yaml.dump(fm, default_flow_style=False, allow_unicode=True)
    if not fm_text.endswith("\n"):
        fm_text += "\n"
    rebuilt = prefix + fm_text + suffix

    # The YAML block may re-order/re-format, but everything outside the
    # fences must be byte-identical, and the block must still round-trip.
    assert rebuilt.startswith(prefix)
    assert rebuilt.endswith(suffix)


def test_read_page_parts_returns_none_for_missing_file(tmp_path: Path):
    assert read_page_parts(tmp_path / "missing.md") is None


def test_read_page_parts_returns_none_when_no_frontmatter_fence(tmp_path: Path):
    path = tmp_path / "no-fence.md"
    path.write_text("Just a plain file, no frontmatter at all.\n", encoding="utf-8")

    assert read_page_parts(path) is None


def test_read_page_parts_returns_none_on_unparseable_yaml(tmp_path: Path):
    path = tmp_path / "broken.md"
    path.write_text("---\nnot: [valid, yaml, :\n---\n\nBody.\n", encoding="utf-8")

    assert read_page_parts(path) is None
