"""Golden test: Hub Page template output matches EXPECTED literal byte-exactly.

Covers ADR-0033 decision 3 / issue #513's `templates.generate_hub_page` — the
entity-style "about this document" synthesis for a Longform Source, with a
chapter wikilink list appended programmatically (not by the LLM) after the
synthesised prose.

The mock LLM returns a fixed body and empty open_questions so the output is
100% deterministic. LangChain types are confined to templates.py per
CODING_STANDARD §2.4 — this test only imports from app.schemas and
app.templates.

Hermetic: no OPENAI_API_KEY required.
"""

from __future__ import annotations

import datetime
from unittest.mock import MagicMock

import app.templates as templates_module
from app.indexer import Section, slugify
from app.templates import generate_hub_page

# ---------------------------------------------------------------------------
# Fixed test data
# ---------------------------------------------------------------------------

FIXED_TS = "2026-05-26T14:30:00Z"
FIXED_NOW = datetime.datetime(2026, 5, 26, 14, 30, 0, tzinfo=datetime.UTC)

SOURCE_FILENAME = "my_book.md"
SOURCE_STEM = "my_book"

SECTIONS = [
    Section(
        id="my_book.md#chapter-one",
        file="my_book.md",
        heading="Chapter One",
        heading_path=["Chapter One"],
        content="The opening chapter introduces the protagonist and setting.",
        tokens=["opening", "chapter", "introduces", "protagonist", "setting"],
    ),
    Section(
        id="my_book.md#chapter-two",
        file="my_book.md",
        heading="Chapter Two",
        heading_path=["Chapter Two"],
        content="The second chapter develops the central conflict.",
        tokens=["second", "chapter", "develops", "central", "conflict"],
    ),
]

# (slug, heading) pairs the caller (ingest._synthesize_longform_drafts) would
# pass in AFTER resolving chapter-page slug collisions.
CHAPTERS = [
    ("chapter-one", "Chapter One"),
    ("chapter-two", "Chapter Two"),
]

FIXED_BODY = (
    "My Book is a novel that follows its protagonist through a central conflict, "
    "told across two chapters."
)

# ---------------------------------------------------------------------------
# Expected output — golden literal
# ---------------------------------------------------------------------------

EXPECTED = """\
<!-- Auto-generated by POST /ingest on 2026-05-26T14:30:00Z.
     Source of truth: docs/my_book.md.
     Manual edits will be overwritten on next ingest — edit the Source instead.
     Exception: the `aliases` field is a curator field and is preserved (ADR-0030). -->

---
aliases: []
created: '2026-05-26T14:30:00Z'
id: my-book
open_questions: []
source_hashes: {}
sources:
- my_book.md#chapter-one
- my_book.md#chapter-two
status: live
type: entity
updated: '2026-05-26T14:30:00Z'
---

# My Book

My Book is a novel that follows its protagonist through a central conflict, told across two chapters.

**Chapters:**

- [[chapter-one]]
- [[chapter-two]]

[Source: my_book.md]
"""


# ---------------------------------------------------------------------------
# Fake LLM
# ---------------------------------------------------------------------------


class _FakeSynthesisOutput:
    def __init__(self):
        self.body = FIXED_BODY
        self.open_questions = []


def _make_fake_llm() -> MagicMock:
    fake_llm = MagicMock()
    fake_chain = MagicMock()
    fake_chain.invoke.return_value = _FakeSynthesisOutput()
    fake_llm.with_structured_output.return_value = fake_chain
    return fake_llm


# ---------------------------------------------------------------------------
# Golden test
# ---------------------------------------------------------------------------


def test_hub_template_golden_output(monkeypatch):
    """generate_hub_page() output matches EXPECTED byte-exactly."""
    fake_llm = _make_fake_llm()
    monkeypatch.setattr(templates_module, "_ingest_llm", fake_llm)
    monkeypatch.setattr(templates_module, "get_ingest_llm", lambda: fake_llm)

    draft = generate_hub_page(
        SECTIONS,
        source_stem=SOURCE_STEM,
        source_filename=SOURCE_FILENAME,
        chapters=CHAPTERS,
        now=FIXED_NOW,
    )

    assert draft.slug == slugify(SOURCE_STEM), (
        f"Expected slug='{slugify(SOURCE_STEM)}', got: {draft.slug!r}"
    )
    assert draft.frontmatter.type == "entity"

    from app.wiki_writer import _render_page

    rendered = _render_page(SOURCE_FILENAME, draft)

    assert rendered == EXPECTED, (
        f"Hub template output does not match EXPECTED.\n"
        f"--- EXPECTED ---\n{EXPECTED!r}\n"
        f"--- GOT ---\n{rendered!r}"
    )


def test_hub_template_no_chapters_omits_chapters_block(monkeypatch):
    """An empty chapters list renders no '**Chapters:**' block at all."""
    fake_llm = _make_fake_llm()
    monkeypatch.setattr(templates_module, "_ingest_llm", fake_llm)
    monkeypatch.setattr(templates_module, "get_ingest_llm", lambda: fake_llm)

    draft = generate_hub_page(
        SECTIONS,
        source_stem=SOURCE_STEM,
        source_filename=SOURCE_FILENAME,
        chapters=[],
        now=FIXED_NOW,
    )

    assert draft.body == FIXED_BODY
    assert "Chapters" not in draft.body
