"""Wiki page writer for ingest-produced synthesis pages.

Provides `write_pages_for_source(source, pages, wiki_dir)` which serialises
one or more `WikiPageDraft` objects to:
  - ``wiki/concepts/<slug>.md``  when ``draft.frontmatter.type == "concept"``
  - ``wiki/entities/<slug>.md``  when ``draft.frontmatter.type == "entity"``

Uses atomic tmp-file + ``os.replace`` write (CODING_STANDARD §2.6).

**Slug collision** across Sources within a single batch call is resolved by
the caller (`ingest.py`) via `resolve_slug_collision(existing_slugs, slug)`.
`write_pages_for_source` itself does NOT deduplicate — it writes whatever slug
the draft carries.  Call `resolve_slug_collision` before building drafts when
processing multiple Sources in one batch.

Orphan detection and re-ingest preservation of the `created` timestamp are
deferred to Slice #3.
"""

from __future__ import annotations

import contextlib
import os
import tempfile
from pathlib import Path

import yaml
from pydantic import BaseModel

from .schemas import WikiPageDraft

# ---------------------------------------------------------------------------
# Result schema
# ---------------------------------------------------------------------------


class WriteResult(BaseModel):
    """Outcome of write_pages_for_source.

    `pages_written` lists relative paths (relative to wiki_dir) for every page
    that was successfully created or overwritten.  `errors` lists
    ``(slug, error_message)`` pairs for any pages that failed.
    """

    pages_written: list[str]
    errors: list[tuple[str, str]]


# ---------------------------------------------------------------------------
# Sentinel comment template
# ---------------------------------------------------------------------------

_SENTINEL_TEMPLATE = (
    "<!-- Auto-generated by POST /ingest on {ts}.\n"
    "     Source of truth: docs/{source}.\n"
    "     Manual edits will be overwritten on next ingest — edit the Source instead. -->"
)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _render_frontmatter(draft: WikiPageDraft) -> str:
    """Serialise the WikiPageFrontmatter to a YAML front-matter block.

    Uses PyYAML's `default_flow_style=False` for human-readable block style.
    The `sources` list renders as a proper YAML sequence.
    """
    fm = draft.frontmatter
    data = {
        "id": fm.id,
        "type": fm.type,
        "created": fm.created,
        "updated": fm.updated,
        "sources": fm.sources,
        "status": fm.status,
        "open_questions": fm.open_questions,
    }
    return yaml.dump(data, default_flow_style=False, allow_unicode=True).rstrip()


def _render_page(source: str, draft: WikiPageDraft) -> str:
    """Render a complete wiki page markdown string from a WikiPageDraft.

    Output structure:
        <sentinel HTML comment>

        ---
        <YAML frontmatter>
        ---

        # <heading>

        <LLM body>

        <citation line>
    """
    sentinel = _SENTINEL_TEMPLATE.format(
        ts=draft.frontmatter.created,
        source=source,
    )
    fm_yaml = _render_frontmatter(draft)
    heading = draft.frontmatter.id.replace("-", " ").title()

    parts = [
        sentinel,
        "",
        "---",
        fm_yaml,
        "---",
        "",
        f"# {heading}",
        "",
        draft.body,
        "",
        draft.citation_line,
    ]
    return "\n".join(parts) + "\n"


def _type_subdir(page_type: str) -> str:
    """Map a SourceType to its wiki subdirectory name."""
    if page_type == "entity":
        return "entities"
    return "concepts"


# ---------------------------------------------------------------------------
# Slug collision helper (used by ingest.py batch loop)
# ---------------------------------------------------------------------------


def resolve_slug_collision(used_slugs: set[str], slug: str) -> str:
    """Return a collision-safe slug by appending -2, -3, … suffixes.

    Checks `used_slugs` (a mutable set maintained by the caller) and updates
    it in place by adding the chosen slug before returning.

    The convention matches indexer.py rule 9 and CONTEXT.md Citation format.

    Args:
        used_slugs: Set of slugs already committed (mutated in place).
        slug:       Desired slug.

    Returns:
        The original slug if not already used, otherwise ``slug-2``,
        ``slug-3``, etc.
    """
    if slug not in used_slugs:
        used_slugs.add(slug)
        return slug

    counter = 2
    while True:
        candidate = f"{slug}-{counter}"
        if candidate not in used_slugs:
            used_slugs.add(candidate)
            return candidate
        counter += 1


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def write_pages_for_source(
    source: str,
    pages: list[WikiPageDraft],
    wiki_dir: Path | None = None,
) -> WriteResult:
    """Write wiki synthesis pages for one Source atomically.

    Each page in `pages` is written to ``wiki_dir/<type_subdir>/<slug>.md``
    where ``type_subdir`` is "concepts" or "entities" based on
    ``draft.frontmatter.type``.  Uses a tmp-file + ``os.replace`` for
    atomicity (CODING_STANDARD §2.6).  Parent directories are created as needed.

    Args:
        source:   Bare Source filename, e.g. ``"refund_policy.md"``.
        pages:    List of WikiPageDraft objects to write.
        wiki_dir: Root wiki directory.  Defaults to the repo-level ``wiki/``
                  directory via the same import-time path resolution used by
                  ``indexer.WIKI_DIR``.  Tests override this with ``tmp_path``.

    Returns:
        WriteResult with ``pages_written`` (relative paths) and ``errors``
        (per-slug failures, if any).
    """
    if wiki_dir is None:
        # Import at call time to pick up monkeypatched WIKI_DIR in tests.
        from . import indexer

        wiki_dir = indexer.WIKI_DIR

    pages_written: list[str] = []
    errors: list[tuple[str, str]] = []

    for draft in pages:
        slug = draft.slug
        subdir = _type_subdir(draft.frontmatter.type)
        target_dir = wiki_dir / subdir
        page_path = target_dir / f"{slug}.md"
        relative_path = f"{subdir}/{slug}.md"

        try:
            target_dir.mkdir(parents=True, exist_ok=True)
            text = _render_page(source, draft)

            # Atomic write: tmp file in same dir, then os.replace
            tmp_fd, tmp_path_str = tempfile.mkstemp(
                dir=target_dir,
                suffix=".tmp",
                prefix=f"{slug}_",
            )
            try:
                with os.fdopen(tmp_fd, "w", encoding="utf-8") as fh:
                    fh.write(text)
                os.replace(tmp_path_str, page_path)
            except Exception:
                with contextlib.suppress(OSError):
                    os.unlink(tmp_path_str)
                raise

            pages_written.append(relative_path)

        except Exception as exc:  # noqa: BLE001
            errors.append((slug, f"{type(exc).__name__}: {exc}"))

    return WriteResult(pages_written=pages_written, errors=errors)
