"""Wiki Index projection module.

Provides two public functions for Phase 2 Wiki Index Generation (PRD #17):

- ``project_wiki_index`` — pure function: takes the in-memory Section list
  and returns the full markdown string for ``wiki/index.md``. No IO. Fully
  deterministic — same input produces byte-identical output across runs.

- ``write_wiki_index`` — filesystem wrapper: calls ``project_wiki_index``,
  writes the result atomically (tmp → ``os.replace``), creates ``wiki_dir``
  if absent, and never raises on filesystem errors (returns a failure tuple
  instead).

Neither function modifies the BM25 index state in ``indexer.py``.
Per ADR-0003 / PRD #17, this module is the data plane for the wiki layer;
wiring it into ``build_index`` is deferred to Slice #2.
"""

from __future__ import annotations

import contextlib
import os
import tempfile
from pathlib import Path

from .indexer import WIKI_DIR, Section

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def project_wiki_index(sections: list[Section]) -> str:
    """Return the full markdown string for wiki/index.md.

    Pure function — no filesystem access, no global state mutation, no logging.
    Deterministic: same ``sections`` list always produces the same bytes.

    Projection layout (per PRD #17):

    1. HTML comment header.
    2. Blank line, then ``# Wiki Index``.
    3. Blank line, then stats blockquote: ``> N Sources, M Sections indexed.``
    4. For each Source (alphabetical by filename), an H2 with the bare
       filename, followed by a bullet list in file-appearance order.
    5. Bullet format:
       - Slug-bearing: ``- [<heading>](../docs/<file>#<slug>) — `<id>```
       - Bare-filename (id == filename, no ``#``):
         ``- [<filename>](../docs/<filename>) — `<filename>```
    6. Trailing newline (``text.rstrip() + "\\n"``).
    7. Empty sections list → placeholder body instead of H2 blocks.

    Args:
        sections: In-memory Section list from ``indexer.py``.

    Returns:
        Full markdown string, always ending with a single newline.
    """
    header = (
        "<!-- Auto-generated by POST /index — manual edits will be overwritten."
        " Regenerate by re-running /index. -->"
    )

    if not sections:
        parts = [
            header,
            "",
            "# Wiki Index",
            "",
            "> 0 Sources, 0 Sections indexed.",
            "",
            "_(No Sources indexed yet — run `POST /index` after adding files to `docs/`.)_",
        ]
        return "\n".join(parts).rstrip() + "\n"

    # Group sections by file, preserving file-appearance order within each group.
    # Build an ordered dict keyed by filename (sorted alphabetically later).
    file_to_sections: dict[str, list[Section]] = {}
    for sec in sections:
        file_to_sections.setdefault(sec.file, []).append(sec)

    n_sources = len(file_to_sections)
    m_sections = len(sections)

    lines: list[str] = [
        header,
        "",
        "# Wiki Index",
        "",
        f"> {n_sources} Sources, {m_sections} Sections indexed.",
    ]

    for filename in sorted(file_to_sections):
        lines.append("")
        lines.append(f"## {filename}")
        lines.append("")
        for sec in file_to_sections[filename]:
            bullet = _format_bullet(sec)
            lines.append(bullet)

    return "\n".join(lines).rstrip() + "\n"


def write_wiki_index(
    sections: list[Section],
    wiki_dir: Path | None = None,
) -> tuple[bool, Path | None, str | None]:
    """Write the wiki index markdown file atomically.

    Calls ``project_wiki_index(sections)``, writes the result to
    ``<wiki_dir>/index.md`` using a temp-file + ``os.replace`` for atomicity.
    Creates ``wiki_dir`` (including parents) if it does not exist.

    No exception escapes this function. On any filesystem error the function
    returns a failure tuple instead.

    Args:
        sections: In-memory Section list (passed straight to
            ``project_wiki_index``).
        wiki_dir: Directory to write into. Defaults to ``WIKI_DIR`` from
            ``indexer.py`` (``<repo-root>/wiki``).

    Returns:
        ``(True, <absolute Path to index.md>, None)`` on success.
        ``(False, None, "<ExceptionClass>: <message>")`` on any failure.
    """
    if wiki_dir is None:
        wiki_dir = WIKI_DIR

    try:
        wiki_dir.mkdir(parents=True, exist_ok=True)
        text = project_wiki_index(sections)
        index_path = wiki_dir / "index.md"

        # Atomic write: write to a sibling tmp file, then os.replace
        tmp_fd, tmp_path_str = tempfile.mkstemp(dir=wiki_dir, suffix=".tmp", prefix="index_")
        try:
            with os.fdopen(tmp_fd, "w", encoding="utf-8") as fh:
                fh.write(text)
            os.replace(tmp_path_str, index_path)
        except Exception:
            # Best-effort cleanup of the tmp file
            with contextlib.suppress(OSError):
                os.unlink(tmp_path_str)
            raise

        return True, index_path.resolve(), None

    except Exception as exc:  # noqa: BLE001 — intentional broad catch for wrapper contract
        return False, None, f"{type(exc).__name__}: {exc}"


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _format_bullet(sec: Section) -> str:
    """Format one Section as a wiki-index bullet line.

    Bare-filename Sections (``id == file``, no ``#`` anchor) use the
    ``[<filename>](../docs/<filename>)`` link form.  All other Sections
    extract the slug from ``id`` (the part after the ``#``) and use
    ``[<heading>](../docs/<file>#<slug>)``.

    Args:
        sec: A single Section from the index.

    Returns:
        The full bullet string without a trailing newline.
    """
    filename = sec.file
    if "#" not in sec.id:
        # Rule 7 bare-filename section
        link = f"../docs/{filename}"
        display = filename
        code_id = filename
    else:
        slug = sec.id.split("#", 1)[1]
        link = f"../docs/{filename}#{slug}"
        display = sec.heading
        code_id = sec.id

    return f"- [{display}]({link}) — `{code_id}`"
