"""Wiki page writer for ingest-produced synthesis pages.

Provides `write_pages_for_source(source, pages, wiki_dir)` which serialises
one or more `WikiPageDraft` objects to ``wiki/concepts/<slug>.md`` using an
atomic tmp-file + ``os.replace`` write (same pattern as `wiki_index.py` and
`indexer.py` — see CODING_STANDARD §2.6).

This slice handles a single page per call; orphan detection and re-ingest
preservation of the `created` timestamp are deferred to Slice #3.

YAML frontmatter serialisation uses PyYAML (already a dep from indexer.py's
rule-2 frontmatter parsing).  The sentinel HTML comment and the citation line
are written directly as strings — no additional templating library needed.
"""

from __future__ import annotations

import contextlib
import os
import tempfile
from pathlib import Path

import yaml
from pydantic import BaseModel

from .schemas import WikiPageDraft

# ---------------------------------------------------------------------------
# Result schema
# ---------------------------------------------------------------------------


class WriteResult(BaseModel):
    """Outcome of write_pages_for_source.

    `pages_written` lists relative paths (relative to wiki_dir) for every page
    that was successfully created or overwritten.  `errors` lists
    ``(slug, error_message)`` pairs for any pages that failed.
    """

    pages_written: list[str]
    errors: list[tuple[str, str]]


# ---------------------------------------------------------------------------
# Sentinel comment template
# ---------------------------------------------------------------------------

_SENTINEL_TEMPLATE = (
    "<!-- Auto-generated by POST /ingest on {ts}.\n"
    "     Source of truth: docs/{source}.\n"
    "     Manual edits will be overwritten on next ingest — edit the Source instead. -->"
)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _render_frontmatter(draft: WikiPageDraft) -> str:
    """Serialise the WikiPageFrontmatter to a YAML front-matter block.

    Uses PyYAML's `default_flow_style=False` for human-readable block style.
    The `sources` list renders as a proper YAML sequence.
    """
    fm = draft.frontmatter
    data = {
        "id": fm.id,
        "type": fm.type,
        "created": fm.created,
        "updated": fm.updated,
        "sources": fm.sources,
        "status": fm.status,
        "open_questions": fm.open_questions,
    }
    return yaml.dump(data, default_flow_style=False, allow_unicode=True).rstrip()


def _render_page(source: str, draft: WikiPageDraft) -> str:
    """Render a complete wiki page markdown string from a WikiPageDraft.

    Output structure (per Slice #1 spec):
        <sentinel HTML comment>

        ---
        <YAML frontmatter>
        ---

        # <heading>

        <LLM body>

        <citation line>
    """
    sentinel = _SENTINEL_TEMPLATE.format(
        ts=draft.frontmatter.created,
        source=source,
    )
    fm_yaml = _render_frontmatter(draft)
    heading = draft.frontmatter.id.replace("-", " ").title()

    parts = [
        sentinel,
        "",
        "---",
        fm_yaml,
        "---",
        "",
        f"# {heading}",
        "",
        draft.body,
        "",
        draft.citation_line,
    ]
    return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def write_pages_for_source(
    source: str,
    pages: list[WikiPageDraft],
    wiki_dir: Path | None = None,
) -> WriteResult:
    """Write wiki synthesis pages for one Source atomically.

    Each page in `pages` is written to ``wiki_dir/concepts/<slug>.md`` using
    a tmp-file + ``os.replace`` for atomicity (CODING_STANDARD §2.6).  Parent
    directories are created as needed.

    This slice handles `pages` as a single-element list (the first Section of
    the Source only — Slice #2 adds 1:N expansion).

    Args:
        source:   Bare Source filename, e.g. ``"refund_policy.md"``.
        pages:    List of WikiPageDraft objects to write.
        wiki_dir: Root wiki directory.  Defaults to the repo-level ``wiki/``
                  directory via the same import-time path resolution used by
                  ``indexer.WIKI_DIR``.  Tests override this with ``tmp_path``.

    Returns:
        WriteResult with ``pages_written`` (relative paths) and ``errors``
        (per-slug failures, if any).
    """
    if wiki_dir is None:
        # Import at call time to pick up monkeypatched WIKI_DIR in tests.
        from . import indexer

        wiki_dir = indexer.WIKI_DIR

    concepts_dir = wiki_dir / "concepts"
    pages_written: list[str] = []
    errors: list[tuple[str, str]] = []

    for draft in pages:
        slug = draft.slug
        page_path = concepts_dir / f"{slug}.md"
        relative_path = f"concepts/{slug}.md"

        try:
            concepts_dir.mkdir(parents=True, exist_ok=True)
            text = _render_page(source, draft)

            # Atomic write: tmp file in same dir, then os.replace
            tmp_fd, tmp_path_str = tempfile.mkstemp(
                dir=concepts_dir,
                suffix=".tmp",
                prefix=f"{slug}_",
            )
            try:
                with os.fdopen(tmp_fd, "w", encoding="utf-8") as fh:
                    fh.write(text)
                os.replace(tmp_path_str, page_path)
            except Exception:
                with contextlib.suppress(OSError):
                    os.unlink(tmp_path_str)
                raise

            pages_written.append(relative_path)

        except Exception as exc:  # noqa: BLE001
            errors.append((slug, f"{type(exc).__name__}: {exc}"))

    return WriteResult(pages_written=pages_written, errors=errors)
