"""Wiki page writer for ingest-produced synthesis pages.

Provides `write_pages_for_source(source, pages, wiki_dir)` which serialises
one or more `WikiPageDraft` objects to:
  - ``wiki/concepts/<slug>.md``  when ``draft.frontmatter.type == "concept"``
  - ``wiki/entities/<slug>.md``  when ``draft.frontmatter.type == "entity"``

Uses atomic tmp-file + ``os.replace`` write (CODING_STANDARD §2.6).

**Slug collision** across Sources within a single batch call is resolved by
the caller (`ingest.py`) via `resolve_slug_collision(existing_slugs, slug)`.
`write_pages_for_source` itself does NOT deduplicate — it writes whatever slug
the draft carries.  Call `resolve_slug_collision` before building drafts when
processing multiple Sources in one batch.

**Re-ingest correctness** (Slice #3):
  - `read_existing_frontmatter(path)` reads the YAML frontmatter from an
    existing wiki page so the caller can preserve the original `created` timestamp.
  - `delete_orphans(source, current_page_ids, wiki_dir)` removes wiki pages
    derived from `source` whose slug is not in `current_page_ids`.  Scope is
    strictly per-Source: only pages whose ``sources`` frontmatter field contains
    a citation beginning with ``source#`` are candidates for deletion.
  - `write_pages_for_source` now classifies each written page as created
    (first write) or updated (overwrite of existing file).
"""

from __future__ import annotations

import contextlib
import os
import tempfile
from pathlib import Path

import yaml
from pydantic import BaseModel

from .schemas import WikiPageDraft

# ---------------------------------------------------------------------------
# Result schema
# ---------------------------------------------------------------------------


class WriteResult(BaseModel):
    """Outcome of write_pages_for_source.

    `pages_written` lists relative paths (relative to wiki_dir) for every page
    that was successfully created or overwritten.
    `pages_created` lists paths for pages that were written for the first time
    (did not exist on disk before the write).
    `pages_updated` lists paths for pages that already existed and were overwritten.
    `errors` lists ``(slug, error_message)`` pairs for any pages that failed.
    """

    pages_written: list[str]
    pages_created: list[str]
    pages_updated: list[str]
    errors: list[tuple[str, str]]


# ---------------------------------------------------------------------------
# Sentinel comment template
# ---------------------------------------------------------------------------

_SENTINEL_TEMPLATE = (
    "<!-- Auto-generated by POST /ingest on {ts}.\n"
    "     Source of truth: docs/{source}.\n"
    "     Manual edits will be overwritten on next ingest — edit the Source instead. -->"
)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _render_frontmatter(draft: WikiPageDraft) -> str:
    """Serialise the WikiPageFrontmatter to a YAML front-matter block.

    Uses PyYAML's `default_flow_style=False` for human-readable block style.
    The `sources` list renders as a proper YAML sequence.

    The optional `grounding_failure` block is only included when
    ``draft.frontmatter.status == "failed_grounding"`` (Slice #4).
    """
    fm = draft.frontmatter
    data: dict = {
        "id": fm.id,
        "type": fm.type,
        "created": fm.created,
        "updated": fm.updated,
        "sources": fm.sources,
        "status": fm.status,
        "open_questions": fm.open_questions,
    }
    if fm.grounding_failure is not None:
        data["grounding_failure"] = {
            "reason": fm.grounding_failure.reason,
            "unsupported_claims": fm.grounding_failure.unsupported_claims,
        }
    return yaml.dump(data, default_flow_style=False, allow_unicode=True).rstrip()


def _render_page(source: str, draft: WikiPageDraft) -> str:
    """Render a complete wiki page markdown string from a WikiPageDraft.

    Output structure:
        <sentinel HTML comment>

        ---
        <YAML frontmatter>
        ---

        # <heading>

        <LLM body>

        <citation line>
    """
    sentinel = _SENTINEL_TEMPLATE.format(
        ts=draft.frontmatter.created,
        source=source,
    )
    fm_yaml = _render_frontmatter(draft)
    heading = draft.frontmatter.id.replace("-", " ").title()

    parts = [
        sentinel,
        "",
        "---",
        fm_yaml,
        "---",
        "",
        f"# {heading}",
        "",
        draft.body,
        "",
        draft.citation_line,
    ]
    return "\n".join(parts) + "\n"


def _type_subdir(page_type: str) -> str:
    """Map a SourceType to its wiki subdirectory name."""
    if page_type == "entity":
        return "entities"
    return "concepts"


# ---------------------------------------------------------------------------
# Slug collision helper (used by ingest.py batch loop)
# ---------------------------------------------------------------------------


def resolve_slug_collision(used_slugs: set[str], slug: str) -> str:
    """Return a collision-safe slug by appending -2, -3, … suffixes.

    Checks `used_slugs` (a mutable set maintained by the caller) and updates
    it in place by adding the chosen slug before returning.

    The convention matches indexer.py rule 9 and CONTEXT.md Citation format.

    Args:
        used_slugs: Set of slugs already committed (mutated in place).
        slug:       Desired slug.

    Returns:
        The original slug if not already used, otherwise ``slug-2``,
        ``slug-3``, etc.
    """
    if slug not in used_slugs:
        used_slugs.add(slug)
        return slug

    counter = 2
    while True:
        candidate = f"{slug}-{counter}"
        if candidate not in used_slugs:
            used_slugs.add(candidate)
            return candidate
        counter += 1


# ---------------------------------------------------------------------------
# Re-ingest helpers (Slice #3)
# ---------------------------------------------------------------------------


def read_existing_frontmatter(path: Path) -> dict | None:
    """Read the YAML frontmatter from an existing wiki page.

    Used by the ingest pipeline to retrieve the original ``created`` timestamp
    before overwriting a page, so it can be preserved on re-ingest.

    Concurrency note (Phase 3): callers in ``ingest.py`` invoke this function
    OUTSIDE the ``_index_lock`` (the lock only wraps the orphan-delete + write
    step). That is safe under the Phase 3 Q7 grill decision "no concurrent
    ingests" — the only writer of wiki pages is ``ingest_sources`` and it
    holds the lock during its mutations. If Phase 4+ introduces another wiki
    writer or makes ``ingest_sources`` reentrant, fold this call inside the
    lock to close the TOCTOU window between read-for-`created` and the
    eventual atomic overwrite.

    Args:
        path: Absolute path to a wiki page ``.md`` file.

    Returns:
        A dict of frontmatter fields if the file exists and contains a valid
        ``---``-delimited YAML block, or ``None`` if the file is missing,
        unreadable, or has no parseable frontmatter.
    """
    if not path.exists():
        return None
    try:
        content = path.read_text(encoding="utf-8")
    except OSError:
        return None

    # Skip the optional sentinel HTML comment: find the first "---" line
    lines = content.splitlines()
    dash_indices = [i for i, line in enumerate(lines) if line.strip() == "---"]
    if len(dash_indices) < 2:
        return None

    fm_text = "\n".join(lines[dash_indices[0] + 1 : dash_indices[1]])
    try:
        parsed = yaml.safe_load(fm_text)
    except yaml.YAMLError:
        return None

    if not isinstance(parsed, dict):
        return None
    return parsed


def delete_orphans(
    source: str,
    current_page_ids: set[str],
    wiki_dir: Path | None = None,
) -> list[str]:
    """Delete wiki pages derived from ``source`` whose slug is not in ``current_page_ids``.

    Orphan scope is strictly per-Source: only pages whose ``sources`` frontmatter
    field contains a citation beginning with ``source#`` are considered.  Pages
    derived from other Sources are never touched.

    Args:
        source:          Bare Source filename, e.g. ``"refund_policy.md"``.
        current_page_ids: Set of slug strings that should survive (e.g.
                          ``{"cancellation-window", "refund-timeline"}``).
                          Any on-disk page derived from ``source`` whose slug
                          is NOT in this set is deleted.
        wiki_dir:        Root wiki directory.  Defaults to ``indexer.WIKI_DIR``.

    Returns:
        List of relative paths (e.g. ``["concepts/partial-refund.md"]``) for
        every file that was deleted.  Files that could not be deleted are
        silently skipped (best-effort).
    """
    if wiki_dir is None:
        from . import indexer

        wiki_dir = indexer.WIKI_DIR

    deleted: list[str] = []
    citation_prefix = f"{source}#"

    for subdir_name in ("concepts", "entities"):
        subdir = wiki_dir / subdir_name
        if not subdir.exists():
            continue
        for page_path in sorted(subdir.glob("*.md")):
            fm = read_existing_frontmatter(page_path)
            if fm is None:
                continue
            # Only consider pages whose sources list mentions this Source
            page_sources: list = fm.get("sources", [])
            if not any(str(s).startswith(citation_prefix) for s in page_sources):
                continue
            # This page belongs to the source; check if it's an orphan
            page_slug = page_path.stem
            if page_slug not in current_page_ids:
                relative_path = f"{subdir_name}/{page_path.name}"
                with contextlib.suppress(OSError):
                    page_path.unlink()
                deleted.append(relative_path)

    return deleted


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def write_pages_for_source(
    source: str,
    pages: list[WikiPageDraft],
    wiki_dir: Path | None = None,
) -> WriteResult:
    """Write wiki synthesis pages for one Source atomically.

    Each page in `pages` is written to ``wiki_dir/<type_subdir>/<slug>.md``
    where ``type_subdir`` is "concepts" or "entities" based on
    ``draft.frontmatter.type``.  Uses a tmp-file + ``os.replace`` for
    atomicity (CODING_STANDARD §2.6).  Parent directories are created as needed.

    A page is classified as *created* when the target file does not exist before
    the write, and as *updated* when it does.  This allows the ingest orchestrator
    to populate ``IngestSourceResult.pages_created`` / ``pages_updated``
    meaningfully on re-ingest (Slice #3).

    Args:
        source:   Bare Source filename, e.g. ``"refund_policy.md"``.
        pages:    List of WikiPageDraft objects to write.
        wiki_dir: Root wiki directory.  Defaults to the repo-level ``wiki/``
                  directory via the same import-time path resolution used by
                  ``indexer.WIKI_DIR``.  Tests override this with ``tmp_path``.

    Returns:
        WriteResult with ``pages_written``, ``pages_created``, ``pages_updated``
        (relative paths) and ``errors`` (per-slug failures, if any).
    """
    if wiki_dir is None:
        # Import at call time to pick up monkeypatched WIKI_DIR in tests.
        from . import indexer

        wiki_dir = indexer.WIKI_DIR

    pages_written: list[str] = []
    pages_created: list[str] = []
    pages_updated: list[str] = []
    errors: list[tuple[str, str]] = []

    for draft in pages:
        slug = draft.slug
        subdir = _type_subdir(draft.frontmatter.type)
        target_dir = wiki_dir / subdir
        page_path = target_dir / f"{slug}.md"
        relative_path = f"{subdir}/{slug}.md"

        try:
            target_dir.mkdir(parents=True, exist_ok=True)

            # Classify: created vs updated
            is_new = not page_path.exists()

            text = _render_page(source, draft)

            # Atomic write: tmp file in same dir, then os.replace
            tmp_fd, tmp_path_str = tempfile.mkstemp(
                dir=target_dir,
                suffix=".tmp",
                prefix=f"{slug}_",
            )
            try:
                with os.fdopen(tmp_fd, "w", encoding="utf-8") as fh:
                    fh.write(text)
                os.replace(tmp_path_str, page_path)
            except Exception:
                with contextlib.suppress(OSError):
                    os.unlink(tmp_path_str)
                raise

            pages_written.append(relative_path)
            if is_new:
                pages_created.append(relative_path)
            else:
                pages_updated.append(relative_path)

        except Exception as exc:  # noqa: BLE001
            errors.append((slug, f"{type(exc).__name__}: {exc}"))

    return WriteResult(
        pages_written=pages_written,
        pages_created=pages_created,
        pages_updated=pages_updated,
        errors=errors,
    )
