"""Integration tests for ``kb alias add`` (issue #409 / ADR-0030 decision 3).

``kb alias add <alias> <page-slug>`` wraps ``markdown_kb.app.pages.add_alias``
directly — Direct-class, human-surfaces-only (no MCP equivalent, mirroring
``kb qa``'s own rationale). Tests use typer's CliRunner in-process against
real ``wiki/entities|concepts/*.md`` fixtures planted under the
conftest-redirected ``tmp_path``/wiki dir (the autouse ``_isolate_module_state``
fixture in conftest.py redirects ``markdown_kb.app.indexer.WIKI_DIR``, which
``pages.py`` resolves at call time).
"""

from __future__ import annotations

from pathlib import Path

import yaml
from typer.testing import CliRunner

runner = CliRunner()


def _write_page(
    wiki_dir: Path,
    slug: str,
    *,
    subdir: str = "concepts",
    aliases: list[str] | None = None,
) -> Path:
    page_dir = wiki_dir / subdir
    page_dir.mkdir(parents=True, exist_ok=True)
    frontmatter: dict = {
        "id": slug,
        "type": subdir.rstrip("s"),
        "created": "2026-01-01T00:00:00Z",
        "updated": "2026-01-01T00:00:00Z",
        "sources": ["policy.md#s"],
        "status": "live",
        "open_questions": [],
    }
    if aliases is not None:
        frontmatter["aliases"] = aliases
    fm_yaml = yaml.dump(frontmatter, default_flow_style=False, allow_unicode=True)
    content = (
        f"<!-- Auto-generated by POST /ingest. -->\n\n---\n{fm_yaml}---\n\n# {slug}\n\nBody.\n"
    )
    page_path = page_dir / f"{slug}.md"
    page_path.write_text(content, encoding="utf-8")
    return page_path


def _wiki_dir() -> Path:
    import markdown_kb.app.indexer as indexer_mod

    return indexer_mod.WIKI_DIR


def test_alias_add_succeeds_and_writes_frontmatter():
    from kb_cli.main import app

    page_path = _write_page(_wiki_dir(), "replacement-payment-methods")

    result = runner.invoke(app, ["alias", "add", "PayPal", "replacement-payment-methods"])
    assert result.exit_code == 0, result.output
    assert "Assigned alias 'PayPal'" in result.output
    assert "replacement-payment-methods" in result.output

    fm = yaml.safe_load(page_path.read_text(encoding="utf-8").split("---", 2)[1])
    assert fm["aliases"] == ["PayPal"]


def test_alias_add_not_found_exits_nonzero():
    from kb_cli.main import app

    result = runner.invoke(app, ["alias", "add", "PayPal", "never-created"])
    assert result.exit_code != 0
    assert "not found" in result.output.lower()


def test_alias_add_blank_alias_exits_nonzero():
    from kb_cli.main import app

    _write_page(_wiki_dir(), "some-page")

    result = runner.invoke(app, ["alias", "add", "   ", "some-page"])
    assert result.exit_code != 0


def test_alias_add_collision_with_real_slug_exits_nonzero_naming_owner():
    from kb_cli.main import app

    _write_page(_wiki_dir(), "target-page")
    _write_page(_wiki_dir(), "other-page")

    result = runner.invoke(app, ["alias", "add", "other-page", "target-page"])
    assert result.exit_code != 0
    assert "other-page" in result.output


def test_alias_add_collision_with_another_pages_alias_exits_nonzero_naming_owner():
    from kb_cli.main import app

    _write_page(_wiki_dir(), "target-page")
    _write_page(_wiki_dir(), "owner-page", aliases=["shared-alias"])

    result = runner.invoke(app, ["alias", "add", "shared-alias", "target-page"])
    assert result.exit_code != 0
    assert "owner-page" in result.output


def test_alias_add_is_idempotent():
    from kb_cli.main import app

    page_path = _write_page(_wiki_dir(), "target-page", aliases=["PayPal"])

    result = runner.invoke(app, ["alias", "add", "PayPal", "target-page"])
    assert result.exit_code == 0, result.output

    fm = yaml.safe_load(page_path.read_text(encoding="utf-8").split("---", 2)[1])
    assert fm["aliases"] == ["PayPal"]
