"""Tests for wiki_index.project_wiki_index — pure projection function.

Covers:
  - Golden-file test against the 3-fixture wiki corpus (byte-exact).
  - Edge case: empty sections list produces the empty-body string.
  - Edge case: alphabetical ordering by slug (non-alpha insertion).
  - Edge case: bare-slug Section (no heading, no '#' anchor).
  - Edge case: slug-collision Section (the -2 suffix is preserved verbatim).
"""

from __future__ import annotations

from pathlib import Path

import app.indexer as _indexer
from app.indexer import Section
from app.wiki_index import project_wiki_index

# Path to hand-written wiki fixtures used across Phase 4 tests.
_WIKI_FIXTURES = Path(__file__).resolve().parents[1] / "fixtures" / "wiki"

# ---------------------------------------------------------------------------
# Golden file expectation (byte-exact, per issue #18 AC)
# ---------------------------------------------------------------------------
# Reflects the 3-fixture wiki corpus (acme-shop, cancellation-window, refund-timeline).
# Section IDs use A2 bare-slug form (slug#slug) and headings use wiki-page titles.
# The ../docs/ link prefix is what project_wiki_index produces from Section.file.

EXPECTED = """\
<!-- Auto-generated by POST /index — manual edits will be overwritten. Regenerate by re-running /index. -->

# Wiki Index

> 3 Sources, 3 Sections indexed.

## acme-shop

- [Acme Shop](../docs/acme-shop#acme-shop) — `acme-shop#acme-shop`

## cancellation-window

- [Cancellation Window](../docs/cancellation-window#cancellation-window) — `cancellation-window#cancellation-window`

## refund-timeline

- [Refund Timeline](../docs/refund-timeline#refund-timeline) — `refund-timeline#refund-timeline`
"""

EMPTY_EXPECTED = """\
<!-- Auto-generated by POST /index — manual edits will be overwritten. Regenerate by re-running /index. -->

# Wiki Index

> 0 Sources, 0 Sections indexed.

_(No Sources indexed yet — run `POST /index` after adding files to `docs/`.)_
"""


# ---------------------------------------------------------------------------
# Golden-file test — wiki fixture corpus
# ---------------------------------------------------------------------------


def test_golden_file_wiki_corpus(tmp_path, monkeypatch):
    """project_wiki_index produces byte-exact output for the 3-fixture wiki corpus.

    Indexes the hand-written fixtures (acme-shop entity + cancellation-window
    + refund-timeline concepts) via build_index() so that Section IDs use the
    A2 bare-slug form (slug#slug). Verifies byte-exact output against EXPECTED.
    """
    # Set up tmp wiki dirs populated from the hand-written fixtures.
    wiki_dir = tmp_path / "wiki"
    entities_dir = wiki_dir / "entities"
    concepts_dir = wiki_dir / "concepts"
    entities_dir.mkdir(parents=True)
    concepts_dir.mkdir(parents=True)

    (entities_dir / "acme-shop.md").write_bytes(
        (_WIKI_FIXTURES / "entities" / "acme-shop.md").read_bytes()
    )
    (concepts_dir / "cancellation-window.md").write_bytes(
        (_WIKI_FIXTURES / "concepts" / "cancellation-window.md").read_bytes()
    )
    (concepts_dir / "refund-timeline.md").write_bytes(
        (_WIKI_FIXTURES / "concepts" / "refund-timeline.md").read_bytes()
    )

    # Point SOURCE_DIRS and WIKI_DIR at the tmp wiki dirs so build_index() uses
    # the bare-slug source_id path (wiki-derived page IDs).
    monkeypatch.setattr(_indexer, "WIKI_DIR", wiki_dir)
    monkeypatch.setattr(_indexer, "SOURCE_DIRS", [entities_dir, concepts_dir])

    _indexer.build_index()
    try:
        result = project_wiki_index(_indexer.sections)
        assert result == EXPECTED
    finally:
        _indexer.sections.clear()


# ---------------------------------------------------------------------------
# Edge cases
# ---------------------------------------------------------------------------


def test_empty_sections():
    """project_wiki_index([]) produces the empty-body placeholder string."""
    result = project_wiki_index([])
    assert result == EMPTY_EXPECTED


def test_alphabetical_ordering():
    """Sources are listed alphabetically by slug regardless of insertion order."""
    sections = [
        Section(
            id="c#intro",
            file="c",
            heading="Intro",
            heading_path=["Intro"],
            content="some content",
            tokens=["some", "content"],
        ),
        Section(
            id="a#intro",
            file="a",
            heading="Intro",
            heading_path=["Intro"],
            content="some content",
            tokens=["some", "content"],
        ),
        Section(
            id="b#intro",
            file="b",
            heading="Intro",
            heading_path=["Intro"],
            content="some content",
            tokens=["some", "content"],
        ),
    ]
    result = project_wiki_index(sections)
    a_pos = result.index("## a")
    b_pos = result.index("## b")
    c_pos = result.index("## c")
    assert a_pos < b_pos < c_pos


def test_bare_filename_section():
    """A Section with id == slug (no '#') uses the bare-slug bullet format."""
    sections = [
        Section(
            id="notes",
            file="notes",
            heading="notes",
            heading_path=["notes"],
            content="some notes",
            tokens=["some", "notes"],
        ),
    ]
    result = project_wiki_index(sections)
    assert "## notes" in result
    assert "- [notes](../docs/notes) — `notes`" in result


def test_slug_collision_suffix_preserved():
    """A slug-collision Section with id 'account-help#overview-2' preserves the -2 suffix."""
    sections = [
        Section(
            id="account-help#overview-2",
            file="account-help",
            heading="Overview",
            heading_path=["Overview"],
            content="some content",
            tokens=["some", "content"],
        ),
    ]
    result = project_wiki_index(sections)
    assert "- [Overview](../docs/account-help#overview-2) — `account-help#overview-2`" in result
