"""Tests for wiki_index.project_wiki_index — pure projection function.

Covers:
  - Golden-file test against the real 3-Source docs/ corpus (byte-exact).
  - Edge case: empty sections list produces the empty-body string.
  - Edge case: alphabetical ordering by filename (non-alpha insertion).
  - Edge case: bare-filename Section (no heading, no slug).
  - Edge case: slug-collision Section (the -2 suffix is preserved verbatim).
"""

from __future__ import annotations

from pathlib import Path

import app.indexer as _indexer
from app.indexer import Section
from app.wiki_index import project_wiki_index

# ---------------------------------------------------------------------------
# Golden file expectation (byte-exact, per issue #18 AC)
# ---------------------------------------------------------------------------

REAL_DOCS = Path(__file__).resolve().parents[3] / "docs"

EXPECTED = """\
<!-- Auto-generated by POST /index — manual edits will be overwritten. Regenerate by re-running /index. -->

# Wiki Index

> 3 Sources, 9 Sections indexed.

## account_help.md

- [Change Email Address](../docs/account_help.md#change-email-address) — `account_help.md#change-email-address`
- [Reset Password](../docs/account_help.md#reset-password) — `account_help.md#reset-password`
- [Delete Account](../docs/account_help.md#delete-account) — `account_help.md#delete-account`

## refund_policy.md

- [Cancellation Window](../docs/refund_policy.md#cancellation-window) — `refund_policy.md#cancellation-window`
- [Refund Timeline](../docs/refund_policy.md#refund-timeline) — `refund_policy.md#refund-timeline`
- [Non-Refundable Items](../docs/refund_policy.md#non-refundable-items) — `refund_policy.md#non-refundable-items`

## shipping_faq.md

- [Standard Shipping](../docs/shipping_faq.md#standard-shipping) — `shipping_faq.md#standard-shipping`
- [Expedited Shipping](../docs/shipping_faq.md#expedited-shipping) — `shipping_faq.md#expedited-shipping`
- [Tracking Number](../docs/shipping_faq.md#tracking-number) — `shipping_faq.md#tracking-number`
"""

EMPTY_EXPECTED = """\
<!-- Auto-generated by POST /index — manual edits will be overwritten. Regenerate by re-running /index. -->

# Wiki Index

> 0 Sources, 0 Sections indexed.

_(No Sources indexed yet — run `POST /index` after adding files to `docs/`.)_
"""


# ---------------------------------------------------------------------------
# Golden-file test — real corpus
# ---------------------------------------------------------------------------


def test_golden_file_real_corpus(indexed_corpus):
    """project_wiki_index produces byte-exact output for the 3-Source docs/ corpus."""
    result = project_wiki_index(_indexer.sections)
    assert result == EXPECTED


# ---------------------------------------------------------------------------
# Edge cases
# ---------------------------------------------------------------------------


def test_empty_sections():
    """project_wiki_index([]) produces the empty-body placeholder string."""
    result = project_wiki_index([])
    assert result == EMPTY_EXPECTED


def test_alphabetical_ordering():
    """Sources are listed alphabetically by filename regardless of insertion order."""
    sections = [
        Section(
            id="c.md#intro",
            file="c.md",
            heading="Intro",
            heading_path=["Intro"],
            content="some content",
            tokens=["some", "content"],
        ),
        Section(
            id="a.md#intro",
            file="a.md",
            heading="Intro",
            heading_path=["Intro"],
            content="some content",
            tokens=["some", "content"],
        ),
        Section(
            id="b.md#intro",
            file="b.md",
            heading="Intro",
            heading_path=["Intro"],
            content="some content",
            tokens=["some", "content"],
        ),
    ]
    result = project_wiki_index(sections)
    a_pos = result.index("## a.md")
    b_pos = result.index("## b.md")
    c_pos = result.index("## c.md")
    assert a_pos < b_pos < c_pos


def test_bare_filename_section():
    """A Section with id == filename and no slug uses the bare-filename bullet format."""
    sections = [
        Section(
            id="notes.md",
            file="notes.md",
            heading="notes.md",
            heading_path=["notes.md"],
            content="some notes",
            tokens=["some", "notes"],
        ),
    ]
    result = project_wiki_index(sections)
    assert "## notes.md" in result
    assert "- [notes.md](../docs/notes.md) — `notes.md`" in result


def test_slug_collision_suffix_preserved():
    """A slug-collision Section with id 'account_help.md#overview-2' preserves the -2 suffix."""
    sections = [
        Section(
            id="account_help.md#overview-2",
            file="account_help.md",
            heading="Overview",
            heading_path=["Overview"],
            content="some content",
            tokens=["some", "content"],
        ),
    ]
    result = project_wiki_index(sections)
    assert (
        "- [Overview](../docs/account_help.md#overview-2) — `account_help.md#overview-2`" in result
    )
